### ISSUE TITLE
Wrong value reported

### ISSUE THREAD

**Issue by cyberjeff-u8t** [empierre/MyDomoAtHome#122]
The value reported by the api is not the correct one for a "DevShutter" device, here value is 100.

{"id":"78","name":"Volet Salon","type":"DevShutter","params":[{"key":"Status","value":1},{"key":"Level","value":"100"},{"key":"stopable","value":"0"},{"key":"pulsable","value":"0"}]}

but in Domoticz it is 62
  {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Open",
         "Description" : "10/3/2",
         "Favorite" : 0,
         "HardwareID" : 9,
         "HardwareName" : "Dummy KNX",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "0001409D",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2016-06-08 18:50:36",
         "Level" : 62,
         "LevelInt" : 62,
         "MaxDimLevel" : 100,
         "Name" : "Volet Salon",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Open",
         "StrParam1" : "c2NyaXB0Oi8vL3d3dy92b2xldC5waHAgMTAvMi8yIDc4IE9u",
         "StrParam2" : "c2NyaXB0Oi8vL3d3dy92b2xldC5waHAgMTAvMi8yIDc4IE9mZg==",
         "SubType" : "Switch",
         "SwitchType" : "Blinds Percentage",
         "SwitchTypeVal" : 13,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "blinds",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "36",
         "YOffset" : "541",
         "idx" : "78"
      },

**Comment by empierre** [comment]
et tu le reproduits tout le temps ce problème ? 

sur quelle version es-tu ?

**Comment by cyberjeff-u8t** [comment]
Desole pour la reponse tardive.
Je peux reproduire le probleme, par example:

Je mets a jour la valeur du volet avec la commande suivante:
http://192.168.0.6:8080/json.htm?type=command&param=udevice&idx=83&nvalue=1&svalue=65

avec:
nvalue = 1  --> volet ferme
nvalue = 0 --> volet ouvert

Cela se passe bien avec nvalue = 0.
Mais avec nvalue = 1, MyDomoAtHome reporte une valeur de 100.

je suis en v0.1.50

**Comment by empierre** [comment]
as-tu encore le problème en 0.2.6 ?

**Comment by cyberjeff-u8t** [comment]
Salut ,
Oui mais j'ai trouver comment résoudre le problème en modifiant le fichier
mdah.js...

**Comment by empierre** [comment]
ça m'intéressepour savoir si je peux le réincorporer pour tous (et surtout
s'il y a un discriminant....)

**Comment by empierre** [comment]
dusplkicate #129 ?

**Comment by sorampage** [comment]
Bonjour,
J'ai le même soucis avec un selecteur ... impossible a utiliser depuis ImperiHome ... la commande configurée en OFF est tout le temps envoyée ...

**Comment by empierre** [comment]
Hello sorampage, 

  tu pas posté dans deux bugs, l'un est sur une liste à sélection multiple et l'autre ici un sélecteur multiple, je doute que tu aies les deux problèmes en même temps. 

  comme dit sur le forum domoticz (et dans la doc), il me faut le résultat de cette URL (à adapter à ta conf) pour comprendre quel type de switch domoticz t'as assigné: 

 http://domoticz_ip:8080/json.htm?type=devices&filter=all&used=true&order=Name

**Comment by sorampage** [comment]
Salut,

J'utilise un selecteur "Thermostat" qui envois des requettes HTTP a un Orvibo.
J'installe le selecteur sur imperihome, et impossible de l'utiliser. Celuis-ci m'affiche bien les differents choix disponible, mais il execute pour chaques choix un Off.

[Sans titre.txt](https://github.com/empierre/MyDomoAtHome/files/647422/Sans.titre.txt)

**Comment by sorampage** [comment]
Probleme trouvé.
J'avais des espaces dans les nom des valeurs configuré dans le selecteur.
Le remplace l'espace par autre chose genre : "Heat 19°" par "Heat19°" Et tout est ok ....

**Comment by empierre** [comment]
argh oui une limitation d'imperihome...
