### ISSUE TITLE
MyDomoAtHome_0.1.51 - Sub-process dpkg returned an error code (1)

### ISSUE THREAD

**Issue by TroisSix** [empierre/MyDomoAtHome#124]
Bonjour empierre,

J'ai un pi2, j'avais réussi à bien installer et configurer mon mdah avec la première version (sans nodeJS) et  avec la nouvelle version (nodeJS), et tout fonctionnait très bien avec mon ImperiHome, la classe :-)

Sauf que j'ai dû faire des mauvaises manipulations en voulant installer nginx, en désinstallant node, mdah, réinstallant, etc.
Depuis quelques jours, impossible de ré-installer mdah, j'ai un message d'erreur pendant l'install:
avec **sudo apt-get install MyDomoAtHome**:

```
Lecture des listes de paquets…
Construction de l'arbre des dépendances…
Lecture des informations d'état…
Les NOUVEAUX paquets suivants seront installés :
  MyDomoAtHome
0 mis à jour, 1 nouvellement installés, 0 à enlever et 0 non mis à jour.
Il est nécessaire de prendre 0 o/6 229 ko dans les archives.
Après cette opération, 35,7 Mo d'espace disque supplémentaires seront utilisés.
(Lecture de la base de données... 
(Lecture de la base de données... 5%
...
(Lecture de la base de données... 100%
(Lecture de la base de données... 81851 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../MyDomoAtHome_0.1.51_all.deb ...
**dpkg: erreur de traitement de l'archive /var/cache/apt/archives/MyDomoAtHome_0.1.51_all.deb (--unpack) :
 le sous-processus nouveau script pre-installation a retourné une erreur de sortie d'état 1**
Des erreurs ont été rencontrées pendant l'exécution :
 /var/cache/apt/archives/MyDomoAtHome_0.1.51_all.deb
**E: Sub-process /usr/bin/dpkg returned an error code (1)**
```

J'ai essayé la désinstall, mais le paquet MyDomoAtHome "n'est pas installé".
J'ai tenté

```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
sudo apt-get install -f
```

le vidage du fichier /var/lib/dpkg/info/mydomoathome.postrm en mettant 

```
#!/bin/bash
/bin/true
```

j'ai tenté aussi la suppression de /var/lib/dpkg/info/mydomoathome.list

Quand je fais **sudo dpkg --list |grep node** --> NodeJS est bien présent en version 4.2.2
Quand je fais **sudo dpkg --list |grep npm** --> NPM est bien présent en version 2.14.7
PS: **node --version** et **npm --version** ne retournent rien en console.
Et quand j'ai installé npm avec la commande **sudo npm install -g npm@2.x**, ça n'affichait rien, normal? :(

Merci pour vos lumières, car là ça dépasse mes compétences de petit unixien ;-)

**Comment by TroisSix** [comment]
Je me réponds à moi-même si ça peut aider d'autres, même s'il y a certainement mieux que ce que j'ai fait...
J'avais un conflit je pense avec le paquet npm, j'ai donc finalement fait:

```
sudo rm -f /usr/local/bin/npm
sudo ln -s /usr/bin/npm /usr/local/bin/npm
```

Et en réinstallant le package mdah avec apt-get, c'est passé ;-)

Sauf que maintenant je me retrouve avec ça:

```
mydomoathome.service - MDAH ISS Rest interface for Domoticz to Imperihome
   Loaded: loaded (/etc/systemd/system/mydomoathome.service; enabled)
   Active: failed (Result: start-limit) since mer. 2016-07-13 14:22:23 CEST; 5min ago
   Process: 7597 ExecStart=/usr/share/mydomoathome/bin/mydomoathome (code=exited, status=1/FAILURE)
  Process: 7594 ExecStartPre=/bin/chmod 755 /run/mydomoathome (code=exited, status=0/SUCCESS)
  Process: 7591 ExecStartPre=/bin/chown www-data:www-data /etc/mydomoathome/config.json (code=exited, status=0/SUCCESS)
  Process: 7588 ExecStartPre=/bin/chown www-data:www-data /run/mydomoathome (code=exited, status=0/SUCCESS)
  Process: 7585 ExecStartPre=/bin/mkdir -p /run/mydomoathome (code=exited, status=0/SUCCESS)
 Main PID: 7597 (code=exited, status=1/FAILURE) 

juil. 13 14:22:23 raspberrypi systemd[1]: Unit mydomoathome.service entered failed state.
juil. 13 14:22:23 raspberrypi systemd[1]: mydomoathome.service holdoff time over, scheduling restart.
juil. 13 14:22:23 raspberrypi systemd[1]: Stopping MDAH ISS Rest interface for Domoticz to Imperihome...
juil. 13 14:22:23 raspberrypi systemd[1]: Starting MDAH ISS Rest interface for Domoticz to Imperihome...
juil. 13 14:22:23 raspberrypi systemd[1]: mydomoathome.service start request repeated too quickly, refusing to start.
juil. 13 14:22:23 raspberrypi systemd[1]: Failed to start MDAH ISS Rest interface for Domoticz to Imperihome.
juil. 13 14:22:23 raspberrypi systemd[1]: Unit mydomoathome.service entered failed state.
```

Un soucis se cache toujours derrière un soucis, enfin pour moi lol

Si quelqu'un a une idée je suis preneur? (quitte à ré-ouvrir une "issue"), je vais quand même continuer mes recherches ;-)

**Comment by empierre** [comment]
que te donnes :

/usr/share/mydomoathome/bin/mydomoathome

**Comment by TroisSix** [comment]
Hello,

Euh ça ne retourne rien :-(

2016-07-13 16:22 GMT+02:00 Emmanuel notifications@github.com:

**Comment by empierre** [comment]
as tu le fichier ?

si tu lances node suivi du chemin précédent cela donne quoi ?

**Comment by TroisSix** [comment]
En fait node seul ne donne rien:
$ node /usr/share/mydomoathome/bin/mydomoathome

Quand je rajoute le /usr/bin, c'est mieux mais message qui ne me parle pas
:-)
$ /usr/bin/node /usr/share/mydomoathome/bin/mydomoathome
/usr/share/mydomoathome/bin/mydomoathome:2

# This file was autogenerated by node-deb 0.1.6

^

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

Mmmh :-(

**Comment by TroisSix** [comment]
Et dans le fichier j'ai:
$ cat /usr/share/mydomoathome/bin/mydomoathome
#!/bin/bash

# This file was autogenerated by node-deb 0.1.6

set -e
set -o pipefail
PIDFILE="/tmp/mdah.pid"
LOGFILE="/var/log/mydomoathome/mdah.log"

cd /usr/share/mydomoathome/app

forever  --minUptime 5000 --spinSleepTime 2000 --max-old-space-size=128 -a
-l $LOGFILE /usr/share/mydomoathome/app/mdah.js

Le mercredi 13 juillet 2016, Sébastien BAREL sebastien.barel@gmail.com a
écrit :

> En fait node seul ne donne rien:
> $ node /usr/share/mydomoathome/bin/mydomoathome
> 
> Quand je rajoute le /usr/bin, c'est mieux mais message qui ne me parle pas
> :-)
> $ /usr/bin/node /usr/share/mydomoathome/bin/mydomoathome
> /usr/share/mydomoathome/bin/mydomoathome:2
> 
> # This file was autogenerated by node-deb 0.1.6
> 
> ^
> 
> SyntaxError: Unexpected token ILLEGAL
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:414:25)
>     at Object.Module._extensions..js (module.js:442:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:311:12)
>     at Function.Module.runMain (module.js:467:10)
>     at startup (node.js:136:18)
>     at node.js:963:3
> 
> Mmmh :-(
> 
> Le mercredi 13 juillet 2016, Emmanuel <notifications@github.com

**Comment by empierre** [comment]
non moi non plus...
tu es sur quelle image de domoticz ?
quelle version est donnée pour ce node ?

**Comment by empierre** [comment]
oui pardon c'est un bash,  donc a lancer en bash -x

**Comment by TroisSix** [comment]
J'ai la dernière version stable de domoticz.

$ node --version
Donne rien :-(

$ /usr/bin/node --version
v4.2.2

Pb d'accès à Node?

**Comment by empierre** [comment]
pas sur...

quelle image de dz,  souvent des choses changent avec...

que donne:
which node
which npm
/usr/bin/node /usr/qhare/mydomoathome/app/mdah.js

**Comment by TroisSix** [comment]
ok:

$ *which node*
/usr/sbin/node
$ *whereis node*
node: /usr/bin/node /usr/sbin/node /usr/include/node
/usr/share/man/man8/node.8.gz /usr/share/man/man1/node.1.gz

$ *which npm*
/usr/bin/npm
$ *whereis npm*
npm: /usr/bin/npm /usr/share/man/man3/npm.3.gz /usr/share/man/man1/npm.1.gz

$ */usr/bin/node /usr/qhare/mydomoathome/app/mdah.js*
module.js:339
    throw err;
    ^

Error: Cannot find module '/usr/qhare/mydomoathome/app/mdah.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3



2016-07-13 19:03 GMT+02:00 Emmanuel <notifications@github.com>:

> pas sur...
>
> quelle image de dz, souvent des choses changent avec...
>
> que donne:
> which node
> which npm
> /usr/bin/node /usr/qhare/mydomoathome/app/mdah.js

**Comment by TroisSix** [comment]
ok:

version de domoticz: v3.4834

$ which node
/usr/sbin/node
$ whereis node
node: /usr/bin/node /usr/sbin/node /usr/include/node
/usr/share/man/man8/node.8.gz /usr/share/man/man1/node.1.gz

$ which npm
/usr/bin/npm
$ whereis npm
npm: /usr/bin/npm /usr/share/man/man3/npm.3.gz /usr/share/man/man1/npm.1.gz

$ /usr/bin/node /usr/qhare/mydomoathome/app/mdah.js
module.js:339
    throw err;
    ^

Error: Cannot find module '/usr/qhare/mydomoathome/app/mdah.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)

2016-07-13 19:03 GMT+02:00 Emmanuel notifications@github.com:

> pas sur...
> 
> quelle image de dz, souvent des choses changent avec...
> 
> que donne:
> which node
> which npm
> /usr/bin/node /usr/qhare/mydomoathome/app/mdah.js

**Comment by empierre** [comment]
remplaces qhare par share,  je suis sur android donc la typo et la mémoire
ne m'aident pas...

**Comment by TroisSix** [comment]
pfff, j'avais même pas vu le q à la place du s, je dois avoir la tête dans
le cul ;-)

$ /usr/bin/node /usr/share/mydomoathome/app/mdah.js

```
error: Global conf parsing issue !
error:  Error: Error parsing your configuration file:
[/etc/mydomoathome/config.json]: Unexpected token }
    at File.loadSync
(/usr/share/mydomoathome/app/node_modules/nconf/lib/nconf/stores/file.js:160:11)
    at Provider.add
(/usr/share/mydomoathome/app/node_modules/nconf/lib/nconf/provider.js:137:23)
    at Provider.use
(/usr/share/mydomoathome/app/node_modules/nconf/lib/nconf/provider.js:110:10)
    at loadGlobalConf (/usr/share/mydomoathome/app/mdah.js:92:15)
    at Object.<anonymous> (/usr/share/mydomoathome/app/mdah.js:128:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
error: Global conf load issue !
error:  Error: Error parsing your configuration file:
[/etc/mydomoathome/config.json]: Unexpected token }
    at File.loadSync
(/usr/share/mydomoathome/app/node_modules/nconf/lib/nconf/stores/file.js:160:11)
    at loadStore
(/usr/share/mydomoathome/app/node_modules/nconf/lib/nconf/provider.js:396:26)
    at
/usr/share/mydomoathome/app/node_modules/nconf/node_modules/async/lib/async.js:356:13
    at async.forEachOf.async.eachOf
(/usr/share/mydomoathome/app/node_modules/nconf/node_modules/async/lib/async.js:233:13)
    at _asyncMap
(/usr/share/mydomoathome/app/node_modules/nconf/node_modules/async/lib/async.js:355:9)
    at Object.map
(/usr/share/mydomoathome/app/node_modules/nconf/node_modules/async/lib/async.js:337:20)
    at loadBatch
(/usr/share/mydomoathome/app/node_modules/nconf/lib/nconf/provider.js:405:11)
    at Provider.load
(/usr/share/mydomoathome/app/node_modules/nconf/lib/nconf/provider.js:449:7)
    at loadConf (/usr/share/mydomoathome/app/mdah.js:102:15)
    at Object.<anonymous> (/usr/share/mydomoathome/app/mdah.js:129:1)
warn: basic configuration not found in /etc/mydomoathome/config.json,
defaulting
warn: domoticz access configuration not found in
/etc/mydomoathome/config.json, defaulting
info: Domoticz server: http://127.0.0.1:8080/json.htm
info: Node version: 4.2.2
info: MDAH version: MyDomoAtHome 0.1.51
info: OS version: Linux linux 4.4.13-v7+
info: Hostname: raspberrypi 192.168.36.58 in /home/pi
/usr/share/mydomoathome
info: MDAH port: 3002
info: Refreshing version cache: v0.1.51
```

CTRL+C pour retrouver la main

```
^Cwarn: Received kill signal, shutting down gracefully.
warn: Closed out remaining connections.
```

Mon fichier json est pourtant bien présent, mais il est peut mal rempli?
Voici son contenu:

```
{
  "app_name": "MyDomoAtHome",
   "auth":
{"username":"mon_username","password":"mon_pwd_avec_caracteres_speciaux"},
   "domoticz": {
        "ssl": true,
        "host": "127.0.0.1",
        "port": "8080",
        "path": "/",
        "auth":
{"username":"mon_username","password":"mon_pwd_avec_caracteres_speciaux"},
   },
  "port": 3002,
  "passcode": ""
}
```

2016-07-13 22:15 GMT+02:00 Emmanuel notifications@github.com:

> remplaces qhare par share, je suis sur android donc la typo et la mémoire
> ne m'aident pas...

**Comment by empierre** [comment]
ok tu as une virgule entre deux}  sur le 2e auth a supprimer

**Comment by TroisSix** [comment]
bien vu !
bizarre, ça ne posait pas de problème avant.
je l'ai supprimée, et quand je lance:
/usr/bin/node /usr/share/mydomoathome/app/mdah.js
info: Domoticz server: https://mon_user:mon_pwd@127.0.0.1:8080/json.htm
info: Node version: 4.2.2
info: MDAH version: MyDomoAtHome 0.1.51
info: OS version: Linux linux 4.4.13-v7+
info: Hostname: raspberrypi ip_de_mon_pi in /home/pi /usr/share/mydomoathome
info: MDAH port: 3002
info: Refreshing version cache: v0.1.51
::ffff:ip_de_mon_telephone - - [14/Jul/2016:07:12:54 +0000] "GET /devices
HTTP/1.1" 401 12 "-" "ImperiHome/404 CFNetwork/758.4.3 Darwin/15.5.0"
info:  url=
https://mon_user:mon_pwd@127.0.0.1:8080/json.htm?type=devices&filter=utility&order=Name,
User-Agent=request
::ffff:ip_de_mon_telephone - mon_user [14/Jul/2016:07:12:54 +0000] "GET
/devices HTTP/1.1" 200 319 "-" "ImperiHome/404 CFNetwork/758.4.3
Darwin/15.5.0"
info:  url=
https://mon_user:mon_pwd@127.0.0.1:8080/json.htm?type=devices&filter=utility&order=Name,
User-Agent=request

PS: j'ai aussi fait un sudo chown pi:pi config.json

et quand je lance le service manuellement:
$ sudo service mydomoathome start
ne retourne rien.

$ sudo service mydomoathome status
● mydomoathome.service - MDAH ISS Rest interface for Domoticz to Imperihome
   Loaded: loaded (/etc/systemd/system/mydomoathome.service; enabled)
   Active: failed (Result: start-limit) since jeu. 2016-07-14 09:20:31
CEST; 2s ago
  Process: 28865 ExecStart=/usr/share/mydomoathome/bin/mydomoathome
(code=exited, status=1/FAILURE)
  Process: 28862 ExecStartPre=/bin/chmod 755 /run/mydomoathome
(code=exited, status=0/SUCCESS)
  Process: 28859 ExecStartPre=/bin/chown www-data:www-data
/etc/mydomoathome/config.json (code=exited, status=0/SUCCESS)
  Process: 28856 ExecStartPre=/bin/chown www-data:www-data
/run/mydomoathome (code=exited, status=0/SUCCESS)
  Process: 28853 ExecStartPre=/bin/mkdir -p /run/mydomoathome (code=exited,
status=0/SUCCESS)
 Main PID: 28865 (code=exited, status=1/FAILURE)

juil. 14 09:20:31 raspberrypi systemd[1]: Unit mydomoathome.service entered
failed state.
juil. 14 09:20:31 raspberrypi systemd[1]: mydomoathome.service holdoff time
over, scheduling restart.
juil. 14 09:20:31 raspberrypi systemd[1]: Stopping MDAH ISS Rest interface
for Domoticz to Imperihome...
juil. 14 09:20:31 raspberrypi systemd[1]: Starting MDAH ISS Rest interface
for Domoticz to Imperihome...
juil. 14 09:20:31 raspberrypi systemd[1]: mydomoathome.service start
request repeated too quickly, refusing to start.
juil. 14 09:20:31 raspberrypi systemd[1]: Failed to start MDAH ISS Rest
interface for Domoticz to Imperihome.
juil. 14 09:20:31 raspberrypi systemd[1]: Unit mydomoathome.service entered
failed state.

ça progresse :-D

2016-07-14 9:10 GMT+02:00 Emmanuel notifications@github.com:

> ok tu as une virgule entre deux} sur le 2e auth a supprimer
>

**Comment by empierre** [comment]
oui.

que donne :

bash -x  /usr/share/mydomoathome/bin/ je sais plus quoi

**Comment by TroisSix** [comment]
$ bash -x /usr/share/mydomoathome/bin/mydomoathome
- set -e
- set -o pipefail
- PIDFILE=/tmp/mdah.pid
- LOGFILE=/var/log/mydomoathome/mdah.log
- cd /usr/share/mydomoathome/app
- forever --minUptime 5000 --spinSleepTime 2000 --max-old-space-size=128 -a -l /var/log/mydomoathome/mdah.log /usr/share/mydomoathome/app/mdah.js

**Comment by empierre** [comment]
donc impeccable,  si tu fais un ps il doit tourner,  raison pour laquelle
le service  ne démarre pas a mon avis.

il faut un reboot pour valider cela

**Comment by TroisSix** [comment]
Oui il y a du mieux.
J'ai fait un reboot, mais le service ne se lance toujours pas:

$ bash -x /usr/share/mydomoathome/bin/mydomoathome
- set -e
- set -o pipefail
- PIDFILE=/tmp/mdah.pid
- LOGFILE=/var/log/mydomoathome/mdah.log
- cd /usr/share/mydomoathome/app
- forever --minUptime 5000 --spinSleepTime 2000 --max-old-space-size=128 -a -l /var/log/mydomoathome/mdah.log /usr/share/mydomoathome/app/mdah.js

$ sudo service mydomoathome start
ne retourne rien

$ sudo service mydomoathome status
● mydomoathome.service - MDAH ISS Rest interface for Domoticz to Imperihome
   Loaded: loaded (/etc/systemd/system/mydomoathome.service; enabled)
   Active: failed (Result: start-limit) since jeu. 2016-07-14 09:54:30 CEST; 1s ago
  Process: 949 ExecStart=/usr/share/mydomoathome/bin/mydomoathome (code=exited, status=1/FAILURE)
  Process: 946 ExecStartPre=/bin/chmod 755 /run/mydomoathome (code=exited, status=0/SUCCESS)
  Process: 943 ExecStartPre=/bin/chown www-data:www-data /etc/mydomoathome/config.json (code=exited, status=0/SUCCESS)
  Process: 940 ExecStartPre=/bin/chown www-data:www-data /run/mydomoathome (code=exited, status=0/SUCCESS)
  Process: 937 ExecStartPre=/bin/mkdir -p /run/mydomoathome (code=exited, status=0/SUCCESS)
 Main PID: 949 (code=exited, status=1/FAILURE)

juil. 14 09:54:30 raspberrypi systemd[1]: Unit mydomoathome.service entered failed state.
juil. 14 09:54:30 raspberrypi systemd[1]: mydomoathome.service holdoff time over, scheduling restart.
juil. 14 09:54:30 raspberrypi systemd[1]: Stopping MDAH ISS Rest interface for Domoticz to Imperihome...
juil. 14 09:54:30 raspberrypi systemd[1]: Starting MDAH ISS Rest interface for Domoticz to Imperihome...
juil. 14 09:54:30 raspberrypi systemd[1]: mydomoathome.service start request repeated too quickly, refusing to start.
juil. 14 09:54:30 raspberrypi systemd[1]: Failed to start MDAH ISS Rest interface for Domoticz to Imperihome.
juil. 14 09:54:30 raspberrypi systemd[1]: Unit mydomoathome.service entered failed state.

pi@raspberrypi:~ $ ps -ef |grep myd
pi        1013   799  1 09:54 pts/0    00:00:00 grep --color=auto myd

Et logiquement, réponse de l'API invalide depuis ImperiHome.

**Comment by empierre** [comment]
qu'as tu dans var/lig/mydo... ?

le seul cas prevu pour ne pas se lancer est si qq'un est sur le port, 3002

**Comment by TroisSix** [comment]
dans /var/log, j'ai juste un dossier mydomoathome contenant un fichier usage.log
C'est celui-ci que tu veux que j'ouvre?
Sinon je n'ai aps d'autres logs pour mydomoathome?

**Comment by empierre** [comment]
oui au cas ou. a essayer aussi

lsof -i tcp:3002

**Comment by TroisSix** [comment]
bon j'ai trouvé en fait ma piste du début qui m'embêtait avec node --version qui ne retournait rien.
j'ai donc recréé le lien symbolique avec ln -s /usr/bin/node /usr/sbin/node
et node --version me retourne bien la version maintenant ;-)

un start de mdah lance bien le service.

lsof -i tcp:3002
ne retourne rien.

en consultant le lien http://ip_domoticz:3002/devices ça me retourne
{"devices":[{"id":"S00","name":"Unable to connect to Domoticz","type":"DevGenericSensor","room":"Utility","params": ....

Du beaucoup mieux ;-)

**Comment by empierre** [comment]
mais qu'as installé ou pas au début pour avoir cela ?

**Comment by TroisSix** [comment]
lol je ne sais pas ;-)
sur mon pi2, bizarrement node et npm ont dû mal s'installer, pourquoi? j'aimerais bien savoir car j'avais fait des apt-get remove et apt-get install proprement pourtant...

bref, ça me tracassait ce --version qui ne donnait rien, et la re-création des liens symboliques a visiblement porté ses fruits puisque mdah s'est mis à fonctionner direct !

enfin j'ai juste dû remettre la virgule entre les deux } pour voir mes devices depuis imperihome.

lsof | grep 3002 ou lsof -i tcp:3002 ne retournent rien, normal? 
(alors que mdah fonctionne bien)

Bref, j'ai quand même rebooté mon pi2, et mdah s'est bien relancé tout seul, donc everything is perfect now ;-)
Merci pour ta dispo, ton mdah est vraiment pratique, top et indispensable :-)

Faudrait maintenant que j'essaye de sécuriser l'ensemble avec à minima un https et un nginx je pense?
Quoiqu'un openvpn est ce qu'il y a de mieux je crois? ;-)

**Comment by empierre** [comment]
ok,  pour lsof il faut le lancer en sudo ☺️

**Comment by TroisSix** [comment]
lol pff j'y avais même pas pensé, en effet c'est beaucoup mieux..
en tout cas merci empierre pour ton aide, mdah commençait vraiment à me manquer ;-)
PS: pour la sécurisation, tu aurais des conseils? tu peux me pm, et je clos ce sujet?

**Comment by empierre** [comment]
pour la secu tu as mis deux mdp,  a part du ssl ou un reverse proxy devant
mais tu n'es pas une entreprise ☺️
