### ISSUE TITLE
Graph issue on sensor

### ISSUE THREAD

**Issue by nicop21** [empierre/MyDomoAtHome#126]
J'ai la configuration suivante : 
- ImperiHome sous iOS (9 et 10)
- MyDomoAtHome sur un Synology DS216j (port 3002)
- mydomoticz sur le même synology (port 8084)
- dans domoticz j'ai configuré un capteur de température hygrométrie via WeatherUnderground que nous nommerons THB

Tout est bien configuré et j'arrive bien à obtenir les valeurs courantes dans l'Apps sur l'iPhone.
Par contre, la visualisation en mode graphique ne fonctionne pas.
Après avoir consulté les logs mydomoathome.log, j'ai vu ce type d'appel :

```
info: GET /devices/1/value/histo/1473712861744/1473885661744
info: 1/
info: 1  temp + humidity + baro value
info: http://127.0.0.1:8084/json.htm?type=graph&sensor=temp + humidity + baro&method=1&idx=1&range=day
```

On se doute ici, que les espaces posent sans doute problème.

après avoir reconstitué l'url directe de cet appel vers domoticz sur un navigateur :
=> `http://ipsynology:8084/json.htm?type=graph&sensor=temp + humidity + baro&method=1&idx=1&range=day`
j'obtiens l'erreur suivante :

```
{
   "status" : "ERR"
}
```

En modifiant l'url en ne spécifiant qu'un seul "sensor", on obtient bien un fichier .json contenant des données : 
`http://ipsynology:8084/json.htm?type=graph&sensor=temp&method=1&idx=1&range=day`

```
{
   "result" : [
      {
         "ba" : "1017",
         "d" : "2016-09-11 00:05",
         "hu" : "60",
         "te" : 19.80
      },
      {
         "ba" : "1017",
         "d" : "2016-09-11 00:10",
         "hu" : "60",
         "te" : 19.80
      },
      {
         "ba" : "1017",
         "d" : "2016-09-11 00:15",
         "hu" : "62",
         "te" : 19.70
      },
      {
         "ba" : "1017",
         "d" : "2016-09-11 00:20",
         "hu" : "62",
         "te" : 19.70
...
...
```

**Comment by empierre** [comment]
Bonjour,

  Domoticz ou mydomoticz ?

  J'ai une idée du problème, mais il arrive pour lequel des 3 courbes demandées ?

**Comment by empierre** [comment]
corrigé en 0.2.6
