### ISSUE TITLE
Please integrate fix for Somfy RTS On/Off switches (wall plug) -- RFY

### ISSUE THREAD

**Issue by ghost** [empierre/MyDomoAtHome#127]
Hello,

in the Domoticz forum, there is a solution to handle RFY based On/Off plugs correctly. Could you please include this in the main code (it's basically adding three lines):

https://www.domoticz.com/forum/viewtopic.php?f=21&t=13560&p=98028#p98028

The change is to add

```
case 'On/Off':
   result.push(DevSwitch(data.result[i]));
   break;
```

at line 2344 in the `case 'RFY'` section.

Thanks a lot!

**Comment by empierre** [comment]
ok done in 0.1.57
