### ISSUE TITLE
rfxcounter unknown

### ISSUE THREAD

**Issue by Zorkny** [empierre/MyDomoAtHome#128]
MDAH[18003]: info:  url=http://127.0.0.1:8080/json.htm?type=devices&filter=utility&order=Name, User-Agent=request
MDAH[18003]: info: Domoticz server - energy devices: {"0000204":"0.0","0000201":"0.0","0000501":"31.8","0000005":"30.0","0000601":"105.1","0000006":"0.0"}
MDAH[18003]: warn: RFX Unknown Elförbrukning 0 RFXMeter counter

How can this be fixed? its a WPC2 RFXcounter in domotics for Energy.

**Comment by empierre** [comment]
sent you an updated file, have you tried out ?

**Comment by Zorkny** [comment]
Sorry, that email got stuck in the spam-filter.
Just installed it and it seems to solve the issue.

**Comment by Zorkny** [comment]
But I cant see this sensor in imperihome, any idea why?

**Comment by empierre** [comment]
looks closed, reopen if not,
