### ISSUE TITLE
Wrong values

### ISSUE THREAD

**Issue by l-t-k** [empierre/MyDomoAtHome#129]
I'm running MyDomoAtHome (v 1.52)  with Domoticz (v3.5837). Domoticz is working as expected, but the MyDomoAtHome is having strange behaviour. My blinds (433 mhz) are shown (in the imperihome app) as the opposite of the value in the domoticz. If it's down in domoticz, it's up according to mydomo.

Furthermore, I've got some wifi lamps (milight) installed as well. Working in domoticz, but in the app (imperihome) they are always OFF. If I turn them on it's working, but a new reload will shown them as 'off'.

I do not have any spaces in the names (#95)

Any idea how to solve this?

**Comment by empierre** [comment]
Hello,

  the main questions is the kind of device they are, Domoticz defines two modes a normal and an inverted. 

  without that information from your devices I can't really help, I would need the json output to test (domoticz at e-nef.Com)

**Comment by l-t-k** [comment]
json output: http://pastebin.com/GJr0hwMr

Seems like the blind problem was just a 'visual' problem. The iOS and Android app are using a contradicting icon for open and closed.

The problem with the milight remains. If change color with the imperihome app it's working as expected. The light shows as 'on' and will be shown as 'on' (also after a refresh). However, as soon as I switch it off and turn it on again (all through the imperihome app) another refresh will show it as 'off' again.

**Comment by empierre** [comment]
And if you do another refresh ? there is an automatic refresh delay you can parametrize in the imperihome app,

**Comment by l-t-k** [comment]
Behaviour is the same as I described. No matter if I trigger a manual refresh or it is just an automatic one.

**Comment by sorampage** [comment]
Hi,
Can you try to change your blinds type by "Venitian Blinds US" ??

**Comment by empierre** [comment]
accepted #141, will package soon, that may correct your issue, can you check on next version ?
reminder: repository has moved to https, please upgrade apt source list.

**Comment by l-t-k** [comment]
No, I can't. I would like to, but I have switched from domoticz to home assistant. Sorry for that
