### ISSUE TITLE
No configuration can be loaded from config.json when running on Windows.

### ISSUE THREAD

**Issue by marivo** [empierre/MyDomoAtHome#130]
When running on Windows, in loadGlobalConf() of mdah.js it is not possible to find the path to the file "/etc/mydomoathome/config.json". 

Also, the loadGlobalConf() does not check for presence of the file, in contrast to loadLocalConf() which is called one line before. 

Therefore, a configuration, even if successfully loaded in loadLocalConf(), is erased by nconf.use called on the non-loaded config file in the loadGlobalConf and thus becomes invalid.

Solution: check for presence of the config file in loadGlobalConf() just as it is done in the loadLocalConf().

Thanks.

**Comment by empierre** [comment]
thanks for the tip, closed as of 0.2.1
