### ISSUE TITLE
Docker Hub image tag latest

### ISSUE THREAD

**Issue by CondormanFr** [empierre/MyDomoAtHome#131]
It seems that since a few version, it 's not possible to select the "latest" tag for the docker image on synology.
![2016-11-13 18_16_12-sino - synology diskstation](https://cloud.githubusercontent.com/assets/2799574/20247476/962b1eac-a9cd-11e6-91d1-3b1aee29b433.jpg)

**Comment by empierre** [comment]
liiks like I deactivated its automated build, doing it now

**Comment by empierre** [comment]
strange for it is here: https://hub.docker.com/r/epierre/iss-mdah/builds/

**Comment by CondormanFr** [comment]
Yes, the tag is visible on docker HUB but not when I select "epierre/iss-mdah" image on synology.
It's really strange

**Comment by empierre** [comment]
maybe try the workaround in the last post here:

https://forum.synology.com/enu/viewtopic.php?t=107508
