### ISSUE TITLE
Wrong values Hue Lamp / Szenes

### ISSUE THREAD

**Issue by MRxCloud** [empierre/MyDomoAtHome#133]
The :3002/devices gives wrong values on my Hue Lamps and Scenes in Domoticz.

They show as off 0 when they are on in Domoticz and the real world:

{"id":"93","name":"Schlafzimmer Hue Lampe","type":"DevRGBLight","room":"Dach","params":[{"key":"Status","value":0}]},
,{"id":"124","name":"Wohnzimmer Hue Lampe","type":"DevRGBLight","room":"EG","params":[{"key":"Status","value":0}]},

**Comment by empierre** [comment]
and what is the device definition on:
curl http://domoticz_ip:domoticz_port/json.htm?type=devices&filter=all&used=true&order=Name

**Comment by MRxCloud** [comment]
Wow, that was fast :-). The definition is:

      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Set Level",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 8,
         "HardwareName" : "Hue",
         "HardwareType" : "Philips Hue Bridge",
         "HardwareTypeVal" : 38,
         "HaveDimmer" : true,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "00000002",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-01-03 15:57:07",
         "Level" : 0,
         "LevelInt" : 200,
         "MaxDimLevel" : 100,
         "Name" : "Schlafzimmer Hue Lampe",
         "Notifications" : "false",
         "PlanID" : "5",
         "PlanIDs" : [ 5 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Set Level",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "RGBW",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Lighting Limitless/Applamp",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "2613",
         "YOffset" : "1418",
         "idx" : "93"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "On",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 8,
         "HardwareName" : "Hue",
         "HardwareType" : "Philips Hue Bridge",
         "HardwareTypeVal" : 38,
         "HaveDimmer" : true,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "000007E7",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-01-03 15:57:08",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Wohnzimmer Hue Lampe",
         "Notifications" : "false",
         "PlanID" : "3",
         "PlanIDs" : [ 3 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "On",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "RGBW",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Lighting Limitless/Applamp",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "1162",
         "YOffset" : "3085",
         "idx" : "124"
      }
   ],

**Comment by empierre** [comment]
result is consistent, level=0 == Off, and this is an on/off, I have no other information to say otherwise

"Level" : 0,
     "LevelInt" : 200,
     "MaxDimLevel" : 100,

"Level" : 0,
     "LevelInt" : 0,
     "MaxDimLevel" : 100,

**Comment by MRxCloud** [comment]
I see, its strange that Domoticz does not change the Level value and only sets the 
`     "Status" : "On",`
Perhaps i have to to change some configuration in Domoticz.

**Comment by empierre** [comment]
this can too be a bug in domoticz as it happens sometimes...

**Comment by MRxCloud** [comment]
Thanks, i will look around and post some information if i find something :-)

**Comment by empierre** [comment]
accepted #141, will package soon, that may correct your issue, can you check on next version ?
reminder: repository has moved to https, please upgrade apt source list.

**Comment by MRxCloud** [comment]
Hi empierre,

thanks for the update. But now my Hue Lamps from domoticz show as always on in imperihome:

Lamp is off:

`{"id":"93","name":"Schlafzimmer Hue Lampe","type":"DevRGBLight","params":[{"key":"Status","value":"1"},{"key":"dimmable","value":"1"},{"key":"Level","value":"0"}]}`

```
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 8,
         "HardwareName" : "Hue",
         "HardwareType" : "Philips Hue Bridge",
         "HardwareTypeVal" : 38,
         "HaveDimmer" : true,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "00000002",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-09-05 22:56:31",
         "Level" : 0,
         "LevelInt" : 144,
         "MaxDimLevel" : 100,
         "Name" : "Schlafzimmer Hue Lampe",
         "Notifications" : "false",
         "PlanID" : "5",
         "PlanIDs" : [ 5 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "RGBW",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Lighting Limitless/Applamp",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "2613",
         "YOffset" : "1418",
         "idx" : "93"
      },
```

**Comment by empierre** [comment]
ok will try something else

**Comment by empierre** [comment]
ok seems today 0.2.19 should fix this

**Comment by MRxCloud** [comment]
Tested it, works like a charm now. Thanks :-)

**Comment by empierre** [comment]
great !
