### ISSUE TITLE
Addition to readme.md 

### ISSUE THREAD

**Issue by Sneeuwtijger** [empierre/MyDomoAtHome#134]
- edit  /etc/mydomoathome/config.json with your values 
Could be enhanced by adding  - sudo nano /etc/mydomoathome/config.json 

- a few lines above the other item a little typo 
Important remark: do not install as roos, but sudo as an unprivilegied user 
 - should be -
Important remark: do not install as root, but sudo as an unprivileged user
.                                                                x.                                           x

**Comment by empierre** [comment]
though I don't understand your last remark, made the correction, thanks !
