### ISSUE TITLE
Stop button not displayed with DOMOTICZ-RFY (RFXCOM) blinds

### ISSUE THREAD

**Issue by fredb45** [empierre/MyDomoAtHome#135]
Hello,

I use domoticz last stable version (Windows)
I have several blinds (RFY SOMFY) with the RFXCOM 433.
In domoticz switch tab, blinds are identified as Type:RFY, RFY, Blinds and there are 3 buttons : Open/stop/close. The 3 buttons works fine

So far, so good but in Imperihome apple version, no stop button displayed (only up/down)... 

DOMOTICZ JSON :  http://X.X.X.X:8080/json.htm?type=devices&filter=all&used=true&order=Name, 

 {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Closed",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RFXtrx433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "000005",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-01-31 20:30:01",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 0,
         "Name" : "Volet bureau",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Closed",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "RFY",
         "SwitchType" : "Blinds",
         "SwitchTypeVal" : 3,
         "Timers" : "false",
         "Type" : "RFY",
         "TypeImg" : "blinds",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "6"
      },

MyDomoAtHome : http://Y.Y.Y.Y:3002/devices, return

{

    "id":"6",
    "name":"Volet bureau",
    "type":"DevShutter",
    "room":"Switches",
    "params":[
        {
            "key":"Status",
            "value":0
        },
        {
            "key":"Level",
            "value":"0"
        },
        {
            "key":"stopable",
            "value":"0"
        },
        {
            "key":"pulsable",
            "value":"0"
        }
    ]
}

what's wrong ? Maybe key "stopable" shoud be "1"

Regards

**Comment by empierre** [comment]
Please try next version (repository to change in apt source list to https)

**Comment by fredb45** [comment]
Hello,

Works fine now.
Thanks A lot.

Fred

**Comment by empierre** [comment]
Great ! Thanks for reporting
