### ISSUE TITLE
No more windows/door open/close sensors

### ISSUE THREAD

**Issue by Philmo67** [empierre/MyDomoAtHome#136]
Hello,
the open/close door contact sensors have disappeared from my DOMO_IP:3002/devices.

DOMO_IP:8080/json.htm?type=devices&filter=all&used=true&order=Name
shows for one of them : 
{
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 90,
         "CustomImage" : 0,
         "Data" : "Closed",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 7,
         "HardwareName" : "Z-Stick",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00000A34",
         "Image" : "Light",
         "InternalState" : "Closed",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-02-24 22:48:13",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Porte Entrée",
         "Notifications" : "false",
         "PlanID" : "11",
         "PlanIDs" : [ 11 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Closed",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Door Contact",
         "SwitchTypeVal" : 11,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "door",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "335"
      }

I am using the latest Domoticz beta version and the latest Mdah version (I just reinstalled it but it doesn't help). Did something change in the latest Domoticz beta that Mdah isn't aware of ?

**Comment by Philmo67** [comment]
Switch type has become "Door Contact" ...

**Comment by empierre** [comment]
same issue here, will adapt

**Comment by Philmo67** [comment]
Thank you !
