### ISSUE TITLE
Cannot stop the mydomoathome: Forever cannot find process with id

### ISSUE THREAD

**Issue by lrybak** [empierre/MyDomoAtHome#137]
Did fresh install as described on: https://www.domoticz.com/wiki/ImperiHome
I can start the process using
$ sudo /etc/init.d/mydomoathome start
But cannot stop it, becouse of the following error
$ sudo /etc/init.d/mydomoathome stop
Shutting down MyDomoAtHome
error:   Forever cannot find process with id: /usr/share/mydomoathome/app/mdah.js

$ npm -v
2.15.11
$ nodejs -v
v4.8.0
$ forever --version
v0.15.2

Ubuntu server 16.04

**Comment by empierre** [comment]
Yes that can happen with the underlying forever process, moving to pm2 just to start stop would have impacts on many installations...

**Comment by lrybak** [comment]
As a workaround I can succesfully start/stop service with the following:
service mydomoathome start
service mydomoathome stop

Do you have any timeline of pm2 migration?

**Comment by empierre** [comment]
not yet, for it would mean testing on Synology, docker, pi1 and pi2...
quite long and difficult, and some beta testers would be needed for it is
very stable so far ;-)

**Comment by lrybak** [comment]
Ok I see. As there is working workaround you can close this issue I guess
