### ISSUE TITLE
Cannot get it to start with https

### ISSUE THREAD

**Issue by jacobhallgren** [empierre/MyDomoAtHome#138]
Hi trying to get MDAH running

I had excluded the MDAH getaway in local networks but still gettings this error

{"devices":[{"id":"S00","name":"Unable to connect to Domoticz","type":"DevGenericSensor","room":"Utility","params":[{"key":"Value","value":"https://172.16.40.14:443/json.htm"}]},{"id":"S01","name":"Please add this gateway in Setup/settings/Local Networks","type":"DevGenericSensor","room":"Utility"}]}

My config.json

{
"app_name": "MyDomoAtHome",
"auth": null,
"domoticz": {
"ssl": true,
"host": "172.16.40.14",
"port": "443",
"path": "/",
"auth": null
},
"port": "3002",
"passcode": ""
}

Auth is off in domoticz and the network is excluded from auth. 

If I run the command from the machine it works: 

curl --insecure https://172.16.40.14/json.htm?type=devices&filter=all&used=true&order=Name

**Comment by empierre** [comment]
hello, sorry didn't see your subject earlier, had no notif...

so domoticz is on another server ? can you ping it ? (looks like). Do you have any error in the logs ? is your certificate custom ? which distro are you on and does it check certificate systématically ?

**Comment by empierre** [comment]
no return
