### ISSUE TITLE
Addition to readme.md about config.json

### ISSUE THREAD

**Issue by canix1** [empierre/MyDomoAtHome#140]
According to the readme.md file it says:
"configuration "config.json" must be in the same directory as the file mdah.js"
Which is it always true. 
For example on my Synology is the file mdah,js in /usr/local/mydomoathome/ but it looks for the config.json file in /etc/mydomoathome/, eventhough it says ./config.json in mdah.js and the file is in /usr/local/mydomoathome/ it doesnt work and the mydomotoathome.log say if can't find it in /etc/mydomoathome/.

So it would make sense to change the line "configuration "config.json" must be in the same directory as the file mdah.js" that it should always be  in /etc/mydomoathome/ for at least Synology.

**Comment by empierre** [comment]
hmmm... it searches for several places, but depending on the system it can be one or the other...

windows must have it in the same place, others not...
