### ISSUE TITLE
DevShutter not seen 

### ISSUE THREAD

**Issue by theduf59** [empierre/MyDomoAtHome#144]
hello, 
My "DevShutter" and "DevShutterInverted" devices are not seen in Imperihome.
I checked ISS API and the key "Status" is not an available option for theses devices.

I changed my mdah.js to comment the Status key and it works fine now.

not sure this is the best implementation so I open this issue so that you could update properly.

best regards

**Comment by empierre** [comment]
Hello,

  can you send me the domoticz view in both opened or closed ? 

  I do not want to harm other working devices, and find the right key,

thanks,

**Comment by theduf59** [comment]
Hello, 
What do you mean by Domoticz view ? 

here is the (partial) result of the GET /devices request I had for my DevShutter : 

```
,
{
"id":"237",
"name":"Volet Cuisine",
"type":"DevShutter",
"room":"Cuisine",
"params":[
{
"key":"Status",
"value":1
},
{
"key":"Level",
"value":"100"
},
{
"key":"stopable",
"value":"0"
},
{
"key":"pulsable",
"value":"0"
}
]
}
```
but according to [http://dev.evertygo.com/api/iss](http://dev.evertygo.com/api/iss) only possible param keys are : 
Device parameter : 
- stopable
- pulseable
- Level

so i edited mdah.js / function DevShutterInverted(data) 
and commented this line : 
`params.push({"key": "Status", "value": status});`

some info on my environment : 
- Latest Domoticz beta on a Rpi3
- mdah on the same Rpi
- Imperihome on a cheap android tablet
- Contrôleur USB Z-Wave+ - Everspring
- Fibaro FGR-222 roller shutter

**Comment by empierre** [comment]
Hello, this is the result for this device of domoticz output to:
	http://domoticz_ip:8080/json.htm?type=devices&filter=all&used=true&order=Name

**Comment by theduf59** [comment]
Hello, Here is partial result of this request : 
http://domoticz_ip:8080/json.htm?type=devices&filter=all&used=true&order=Name



When Shutter is opened : 

`,
{
"AddjMulti":1.0,
"AddjMulti2":1.0,
"AddjValue":0.0,
"AddjValue2":0.0,
"BatteryLevel":255,
"CustomImage":0,
"Data":"Open",
"Description":"",
"Favorite":1,
"HardwareID":12,
"HardwareName":"ZwavePlusEvergspring",
"HardwareType":"OpenZWave USB",
"HardwareTypeVal":21,
"HaveDimmer":true,
"HaveGroupCmd":true,
"HaveTimeout":false,
"ID":"00000401",
"Image":"Light",
"IsSubDevice":false,
"LastUpdate":"2017-09-01 07:13:07",
"Level":100,
"LevelInt":100,
"MaxDimLevel":100,
"Name":"Volet Cuisine",
"Notifications":"false",
"PlanID":"4",
"PlanIDs":[
4
],
"Protected":false,
"ShowNotifications":true,
"SignalLevel":"-",
"Status":"Open",
"StrParam1":"",
"StrParam2":"",
"SubType":"Switch",
"SwitchType":"Blinds Percentage Inverted",
"SwitchTypeVal":16,
"Timers":"true",
"Type":"Light/Switch",
"TypeImg":"blinds",
"Unit":1,
"Used":1,
"UsedByCamera":false,
"XOffset":"0",
"YOffset":"0",
"idx":"237"
},`

when shutter is closed : 

`,
{
"AddjMulti":1.0,
"AddjMulti2":1.0,
"AddjValue":0.0,
"AddjValue2":0.0,
"BatteryLevel":255,
"CustomImage":0,
"Data":"Closed",
"Description":"",
"Favorite":1,
"HardwareID":12,
"HardwareName":"ZwavePlusEvergspring",
"HardwareType":"OpenZWave USB",
"HardwareTypeVal":21,
"HaveDimmer":true,
"HaveGroupCmd":true,
"HaveTimeout":false,
"ID":"00000401",
"Image":"Light",
"IsSubDevice":false,
"LastUpdate":"2017-09-01 07:39:27",
"Level":0,
"LevelInt":0,
"MaxDimLevel":100,
"Name":"Volet Cuisine",
"Notifications":"false",
"PlanID":"4",
"PlanIDs":[
4
],
"Protected":false,
"ShowNotifications":true,
"SignalLevel":"-",
"Status":"Closed",
"StrParam1":"",
"StrParam2":"",
"SubType":"Switch",
"SwitchType":"Blinds Percentage Inverted",
"SwitchTypeVal":16,
"Timers":"true",
"Type":"Light/Switch",
"TypeImg":"blinds",
"Unit":1,
"Used":1,
"UsedByCamera":false,
"XOffset":"0",
"YOffset":"0",
"idx":"237"
},`

**Comment by empierre** [comment]
ok I did not need that, check ISS doc, removed for the blinds and blinds inverted. Check version 0.22.12

**Comment by theduf59** [comment]
Here is what I get when I "sudo apt-get update / upgrade" 

```
dpkg: erreur de traitement de l'archive /var/cache/apt/archives/MyDomoAtHome_0.2.12*_all.deb (--unpack) :
 analyse du fichier '/var/lib/dpkg/tmp.ci/control' vers la ligne 2 paquet 'mydomoathome' :
 erreur dans la chaîne du champ « Version » : « 0.2.12* »: caractère non valable dans le numéro de version 
Des erreurs ont été rencontrées pendant l'exécution :
 /var/cache/apt/archives/MyDomoAtHome_0.2.12*_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by empierre** [comment]
not a good news, repackaging it

**Comment by empierre** [comment]
should be good now
