### ISSUE TITLE
Shutter Level shows level 100 percent opened and closed

### ISSUE THREAD

**Issue by MRxCloud** [empierre/MyDomoAtHome#150]
It sounds like the same bug that was fixed here just with shutters: https://github.com/empierre/MyDomoAtHome/issues/141

Shutter completely open:
```
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Open",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "razberry2",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00001001",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-09-05 11:11:30",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Jalousie Bad OG",
         "Notifications" : "false",
         "PlanID" : "4",
         "PlanIDs" : [ 4 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Open",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Blinds Percentage",
         "SwitchTypeVal" : 13,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "blinds",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "1060",
         "YOffset" : "300",
         "idx" : "204"
      },
```

In mydomo: {"id":"204","name":"Jalousie Bad OG","type":"DevShutter","params":[{"key":"Level","value":"100"},{"key":"stopable","value":"0"},{"key":"pulsable","value":"0"}]}

Shutter completely closed:

```
 {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Closed",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "razberry2",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00001001",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-09-05 11:36:52",
         "Level" : 100,
         "LevelInt" : 100,
         "MaxDimLevel" : 100,
         "Name" : "Jalousie Bad OG",
         "Notifications" : "false",
         "PlanID" : "4",
         "PlanIDs" : [ 4 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Closed",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Blinds Percentage",
         "SwitchTypeVal" : 13,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "blinds",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "1060",
         "YOffset" : "300",
         "idx" : "204"
      },
```

In mydomo: {"id":"204","name":"Jalousie Bad OG","type":"DevShutter","params":[{"key":"Level","value":"100"},{"key":"stopable","value":"0"},{"key":"pulsable","value":"0"}]},

Domoticz stable: 3.8153
MyDomoAtHome: 0.2.15
On Raspberry PI 3 and Fibaro Roller Shutter

**Comment by empierre** [comment]
published package yesterday, tell me if it is good now,

**Comment by MRxCloud** [comment]
Hi empierre,

thanks for your fast answer. Tested now with 0.2.16. Still the same problem:

Shutter is closed:
`     {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Closed",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "razberry2",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00001001",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-09-06 11:05:47",
         "Level" : 100,
         "LevelInt" : 100,
         "MaxDimLevel" : 100,
         "Name" : "Jalousie Bad OG",
         "Notifications" : "false",
         "PlanID" : "4",
         "PlanIDs" : [ 4 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Closed",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Blinds Percentage",
         "SwitchTypeVal" : 13,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "blinds",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "1060",
         "YOffset" : "300",
         "idx" : "204"
      },`

`{"id":"204","name":"Jalousie Bad OG","type":"DevShutter","params":[{"key":"Level","value":"100"},{"key":"stopable","value":"0"},{"key":"pulsable","value":"0"}]}`

**Comment by empierre** [comment]
that device is closed with level 100 and open with level 0, this should be blind inverted !!!

**Comment by empierre** [comment]
I'll push a hack for display, but the result when activating it will be messed up because of their (domoticz) config error

**Comment by MRxCloud** [comment]
Hi empierre,

thanks for the hack. Finally i see in imperihome if the shutter is opened or closed. I dont understand why domoticz give the inverted values. The Fibaro Shutters are configured as non inverted in domoticz and it works normally in the web frontend and the domoticz android app.

Now completely closed shows as 0 %, completely opened as 100 %. The slider is still inverted so 1 % is open and 99 percent nearly closed. Still the most important bug that open and closed shows 100 % is gone so im happy :-)

Thank you for your help and your great project so i can use imperihome with domoticz.

**Comment by xztraz** [comment]
How can the inverted blinds percentage slider bug be solved? i'm having the same issue. should this be fixed in domoticz?
