### ISSUE TITLE
Https Access and remote access

### ISSUE THREAD

**Issue by detxm80** [empierre/MyDomoAtHome#160]
I guys, i've a problem with https configuration. 
I follow the guide but i get 404 page not found if i use https://
http access is all ok

    AppName: MyDomoAtHome
    MDAH: http://192.168.x.58:3002
    Domoticz: http://127.0.0.1:8080/json.htm
    NodeJS: v4.8.7
    Webmanager: EJS
    Renderer: Express

and tihs is my config.json:

{
  "app_name": "MyDomoAtHome",
   "auth": null,
   "tempmode": "C",
   "domoticz": {
        "ssl": false,
        "host": "192.168.x.58",
        "port": "8080",
        "path": "/",
        "auth": { "username": "xxxx", "password": "xxxx" },
   },
  "port": 3002,
  "passcode": ""
}

i try guide " start in https mode" without results.

I've already installed apache2 before mdah installation and it ovelap with domoticz (i think) through 443 port.

Can i use apache2 for remote access (and not ngnix) ? How?
Can you help me to configure it?
Thanks a lot

**Comment by empierre** [comment]
no coma after auth, },} is not allowed here: "auth": { "username": "xxxx", "password": "xxxx" },
