### ISSUE TITLE
How to create multiple instances

### ISSUE THREAD

**Issue by g1r1** [empierre/MyDomoAtHome#167]
How do I go about creating multiple instances? Is there are sample config you can point me to.

**Comment by empierre** [comment]
Hello,

  What configuration do you want to do ? 

  the IH client does recognize only one instance per listening port, configuring several ports (thus launching several mdah) would do the job.

**Comment by g1r1** [comment]
Thanks for the quick reply.

I have three panels running IH and I want to use different domoticz username / passwords for accessing these via MDAH. So for example, bedroom panel will use domoticz user bedroom to connect  and living room will use living username. 

For this, as I see it I will need to run three instances on three ports like 3002, 3003, 3004 (do correct me if I am wrong). I was under the impression you could just create another config inside the config.json with a different app_name and port as mentioned in the readme. But, that clearly didn't work.

Looking at the source, MDAH also only loads one config.json file. So, how do I go about this?

**Comment by empierre** [comment]
yes the best right now would be to have 3 running on 3 ports.

I'm still unsure if imperihome can say it a b or c when getting a list or sending an order

**Comment by empierre** [comment]
Hello, latest 0.2.41 can use end to end user authentication to access a device list
