### ISSUE TITLE
wget

### ISSUE THREAD

**Issue by Znajdzik** [empierre/MyDomoAtHome#177]
I have a problem with using the command  "wget"
wget -d returns "Error 403"
I used the command "curl -a" but similar problem i have with apt-key.

**Comment by empierre** [comment]
Seems the host filters the. Key extension, ticket ongoing...

**Comment by MarcusKlerks** [comment]
Maybe related? sudo apt-update reports following:
Err:8 https://www.e-nef.com/domoticz/mdah  Release
  403  Forbidden
and later on:
E: The repository 'https://www.e-nef.com/domoticz/mdah  Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by SkowronK** [comment]
I have the same.
I was able to download gpg.mykey from other computer and forced 
**sudo apt-key add gpg.mykey**

**sudo apt-key list**
returns:
_pub   rsa4096 2016-03-02 [SC]
      CDD9 6A0B DFFA E454 73B3  8BF2 54CE DB8D A543 5C9B
uid           [ unknown] Emmanuel PIERRE <epierre@e-nef.com>
sub   rsa4096 2016-03-02 [E]_

but then when running 
**sudo apt-get update**
I receive:
_W: The repository 'https://www.e-nef.com/domoticz/mdah  Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://www.e-nef.com/domoticz/mdah/Packages  403  Forbidden
E: Some index files failed to download. They have been ignored, or old ones used instead._

Any idea how to fix this?

**Comment by empierre** [comment]
Hello,

  I can get this one:

https://www.e-nef.com/domoticz/mdah/Packages

  this one works:

wget -qO - https://www.e-nef.com/domoticz/mdah/gpg.mykey | sudo apt-key add
-

seems more a momentous internet issue ?

**Comment by empierre** [comment]
anything related here:
https://github.com/Fourdee/DietPi/issues/2035

**Comment by SkowronK** [comment]
actually it doesn't work:
I cannot even download key 
pi@Domoticz3:~ $ **wget https://www.e-nef.com/domoticz/mdah/gpg.mykey**
_--2019-02-20 22:11:55--  https://www.e-nef.com/domoticz/mdah/gpg.mykey
Resolving www.e-nef.com (www.e-nef.com)... 164.132.235.17, 2001:41d0:301::23
Connecting to www.e-nef.com (www.e-nef.com)|164.132.235.17|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-02-20 22:11:55 ERROR 403: Forbidden._

to avoid confusion downloading random image works.

**Comment by Znajdzik** [comment]
Still not working:
 wget -d http://www.e-nef.com/domoticz/mdah/nodejs_4.4.2_armhf.deb
DEBUG output created by Wget 1.18 on linux-gnueabihf.

Reading HSTS entries from /home/pi/.wget-hsts
URI encoding = `UTF-8'
Converted file name 'nodejs_4.4.2_armhf.deb' (UTF-8) -> 'nodejs_4.4.2_armhf.deb' (UTF-8)
--2019-02-20 22:22:14--  http://www.e-nef.com/domoticz/mdah/nodejs_4.4.2_armhf.deb
Translacja www.e-nef.com (www.e-nef.com)... 164.132.235.17, 2001:41d0:301::23
Caching www.e-nef.com => 164.132.235.17 2001:41d0:301::23
Łączenie się z www.e-nef.com (www.e-nef.com)|164.132.235.17|:80... połączono.
Created socket 3.
Releasing 0x00d28058 (new refcount 1).

---request begin---
GET /domoticz/mdah/nodejs_4.4.2_armhf.deb HTTP/1.1
User-Agent: Wget/1.18 (linux-gnueabihf)
Accept: */*
Accept-Encoding: identity
Host: www.e-nef.com
Connection: Keep-Alive

---request end---
Żądanie HTTP wysłano, oczekiwanie na odpowiedź...
---response begin---
HTTP/1.1 403 Forbidden
Date: Wed, 20 Feb 2019 21:22:14 GMT
Content-Type: text/html; charset=iso-8859-1
Content-Length: 245
Server: Apache
Set-Cookie: SERVERID31394=2321180|XG3FC|XG3FC; path=/
X-IPLB-Instance: 18199

---response end---
403 Forbidden

Stored cookie www.e-nef.com -1 (ANY) / <session> <insecure> [expiry none] SERVERID31394 2321180|XG3FC|XG3FC
Registered socket 3 for persistent reuse.
URI content encoding = `iso-8859-1'
Skipping 245 bytes of body: [<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /domoticz/mdah/nodejs_4.4.2_armhf.deb
on this server.<br />
</p>
</body></html>
] done.
2019-02-20 22:22:14 BŁĄD 403: Forbidden.

~ $ wget https://www.e-nef.com/domoticz/mdah/gpg.mykey
--2019-02-20 22:19:05--  https://www.e-nef.com/domoticz/mdah/gpg.mykey
Translacja www.e-nef.com (www.e-nef.com)... 164.132.235.17, 2001:41d0:301::23
Łączenie się z www.e-nef.com (www.e-nef.com)|164.132.235.17|:443... połączono.
Żądanie HTTP wysłano, oczekiwanie na odpowiedź... 403 Forbidden
2019-02-20 22:19:06 BŁĄD 403: Forbidden.

**Comment by SkowronK** [comment]
I have exactly the same behaviour on my Raspberry pi.
I can download http://www.e-nef.com/domoticz/mdah/nodejs_4.4.2_armhf.deb from my Chrome on win10

**Comment by empierre** [comment]
same here, thanks for pointing the issue... still no real support from my
hosting... nothing in the logs...

**Comment by empierre** [comment]
ok found, the hoster false positive http firewall was blocking me since
they (silently...) changed their config:

[Wed Feb 20 00:00:10 2019] [error] [client 27.78.62.157] ModSecurity:
Access denied with code 403 (phase 2). Matched phrase "curl" at
REQUEST_HEADERS:User-Agent. [file
"/usr/local/apache2/conf/modsecurity/base_rules/modsecurity_crs_35_bad_robots.conf"]
[line "26"] [id "990012"] [rev "2.1.1"] [msg "Rogue web site crawler"]
[data "curl"] [severity "WARNING"] [tag "AUTOMATION/MALICIOUS"] [tag
"WASCTC/WASC-21"] [tag "OWASP_TOP_10/A7"] [tag "PCI/6.5.10"] [hostname
"www.e-nef.com"] [uri "/domoticz/mdah/InRelease"] [unique_id
"XGyKegoXFc8AAAmncFUAAADU"]

should be fixed by now,

**Comment by MarcusKlerks** [comment]
Confirm fixed, thanks.
Mark

**Comment by SkowronK** [comment]
thanks - everything OK
