### ISSUE TITLE
Error with Imperi Home connect : "Could not get devices infos".

### ISSUE THREAD

**Issue by Alitoy** [empierre/MyDomoAtHome#178]
Faced a problem. The ImperialHome(Android) program does not see the device. Error: "Could not get devices infos".
In brouser (Chrome) : http://172.1.xx.xx:3002/devices  - is empty: ERR_EMPTY_RESPONSE.
But this string (in terminal Raspberry Pi) : 
curl http://127.0.0.1:8080/json.htm?type=devices&filter=all&used=true&order=Name
work correctly. Find all devices in Domoticz.
Status:
pi@raspberrypi:~ $ sudo service mydomoathome status
● mydomoathome.service - MDAH ISS Rest interface for Domoticz to Imperihome
   Loaded: loaded (/etc/systemd/system/mydomoathome.service; enabled)
   Active: active (running) since Вс 2019-03-10 20:37:37 +03; 14min ago
  Process: 11511 ExecReload=/bin/kill -HUP $MAINPID (code=exited, status=0/SUCCESS)
  Process: 11526 ExecStartPre=/bin/chmod 755 /run/mydomoathome (code=exited, status=0/SUCCESS)
  Process: 11523 ExecStartPre=/bin/chown www-data:www-data /etc/mydomoathome/config.json (code=exited, status=0/SUCCESS)
  Process: 11520 ExecStartPre=/bin/chown www-data:www-data /run/mydomoathome (code=exited, status=0/SUCCESS)
  Process: 11517 ExecStartPre=/bin/mkdir -p /run/mydomoathome (code=exited, status=0/SUCCESS)
 Main PID: 11529 (mydomoathome)
   CGroup: /system.slice/mydomoathome.service
           ├─11529 /bin/bash /usr/share/mydomoathome/bin/mydomoathome
           ├─11530 node /usr/local/bin/forever --minUptime 5000 --spinSleepTime 2000 --max-old-space-size=128 -a -l /var/log/mydomoathome...
           └─13000 /usr/local/bin/node /usr/share/mydomoathome/app/mdah.js

мар 10 20:49:36 raspberrypi MDAH[11529]: at endReadableNT (_stream_readable.js:1101:12)
мар 10 20:49:36 raspberrypi MDAH[11529]: at process._tickCallback (internal/process/next_tick.js:152:19)
мар 10 20:49:36 raspberrypi MDAH[11529]: error: Forever detected script exited with code: 1
мар 10 20:49:38 raspberrypi MDAH[11529]: error: Script restart attempt #47
мар 10 20:49:40 raspberrypi MDAH[11529]: info: Domoticz server: http://127.0.0.1:8080/json.htm
мар 10 20:49:40 raspberrypi MDAH[11529]: info: Node version: 9.4.0
мар 10 20:49:40 raspberrypi MDAH[11529]: info: MDAH version: MyDomoAtHome 0.2.39
мар 10 20:49:40 raspberrypi MDAH[11529]: info: OS version: Linux linux 4.9.35-v7+
мар 10 20:49:40 raspberrypi MDAH[11529]: info: Hostname: raspberrypi 172.16.0.20 in /var/www /
мар 10 20:49:41 raspberrypi MDAH[11529]: info: Refreshing version cache: v0.2.39
 
ERRORS:
мар 10 20:49:36 raspberrypi MDAH[11529]: at endReadableNT (_stream_readable.js:1101:12)
мар 10 20:49:36 raspberrypi MDAH[11529]: at process._tickCallback (internal/process/next_tick.js:152:19)
мар 10 20:49:36 raspberrypi MDAH[11529]: error: Forever detected script exited with code: 1
мар 10 20:49:38 raspberrypi MDAH[11529]: error: Script restart attempt #47

What could be the problem ?

**Comment by empierre** [comment]
hello, hard to see the issue from this. 

is there someone on 3002 port ? (netstat -ta)

**Comment by empierre** [comment]
any news ?
