### ISSUE TITLE
After update of Imperihome - all devices are gone

### ISSUE THREAD

**Issue by Eternity-again** [empierre/MyDomoAtHome#179]
Yesterday Imperihome Pro updated to v4.3.8 and now all MyDomoAtHome devices are broken/gone. I use v0.2.39 running on a Synology NAS.

If I try to re-add the MyDoMoAtHome object and start the configuration wizard, it shows "Success!" and 21 devices are available. But, the moment I exit the 'add object' page, these devices are all gone.

**Comment by empierre** [comment]
hello, release note says they changed something in 4.3.8 but doc was not updated, sent an email to IH support

**Comment by Eternity-again** [comment]
Thanks empierre!

Will do so!

**Comment by empierre** [comment]
Hello, 

  I tried here with my conf and all is fine.

 do you still have thgis problem ?

**Comment by Eternity-again** [comment]
Sorry, never saw your question!

I managed to solve the issue. Unfortunately the problem is now back again, after I replaced my phone and reinstalled Imperihome on it. And, I forgot how I solved it last time Pffff.
