### ISSUE TITLE
Configuration from Internet: uptodate manual to configure reverse proxy ?

### ISSUE THREAD

**Issue by sspieser** [empierre/MyDomoAtHome#180]
Is there an uptodate explanation on how to configure a front end reverse proxy for MyDomoAtHome & Domoticz, to get access throw it from Internet / Imperi@Home Android app?

I've found various forums etc.. but all seems to link to an obsolete wiki page...

Thanls for your help!

**Comment by empierre** [comment]
In the README.md
https://github.com/empierre/MyDomoAtHome/blob/nodejs/README.md

see section:
Accessing the Gateway from the outide of your network

this is what I use
