### ISSUE TITLE
SyntaxError: 

### ISSUE THREAD

**Issue by tomagoshy23** [empierre/MyDomoAtHome#190]
Bonjour,

Tout d'abord merci pour cette application.
Sur Ubuntu 16.04.6 après installation, j'ai cette erreur "SyntaxError: Block-scoped declarations". Avez vous une idée?. Voici les logs après /etc/init.d/mydomoathome restart

Mar 22 11:08:31 Grange systemd[1]: Stopped MDAH ISS Rest interface for Domoticz to Imperihome.
Mar 22 11:08:31 Grange systemd[1]: Starting MDAH ISS Rest interface for Domoticz to Imperihome...
Mar 22 11:08:31 Grange systemd[1]: Started MDAH ISS Rest interface for Domoticz to Imperihome.
Mar 22 11:08:32 Grange MDAH[26962]: /usr/lib/node_modules/forever/node_modules/forever-monitor/lib/forever-monitor/monitor.js:38
Mar 22 11:08:32 Grange MDAH[26962]:   let execPath = process.execPath;
Mar 22 11:08:32 Grange MDAH[26962]:   ^^^
Mar 22 11:08:32 Grange MDAH[26962]: SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
Mar 22 11:08:32 Grange MDAH[26962]:     at exports.runInThisContext (vm.js:53:16)
Mar 22 11:08:32 Grange MDAH[26962]:     at Module._compile (module.js:373:25)
Mar 22 11:08:32 Grange MDAH[26962]:     at Object.Module._extensions..js (module.js:416:10)
Mar 22 11:08:32 Grange MDAH[26962]:     at Module.load (module.js:343:32)
Mar 22 11:08:32 Grange MDAH[26962]:     at Function.Module._load (module.js:300:12)
Mar 22 11:08:32 Grange MDAH[26962]:     at Module.require (module.js:353:17)
Mar 22 11:08:32 Grange MDAH[26962]:     at require (internal/module.js:12:17)
Mar 22 11:08:32 Grange MDAH[26962]:     at Object.<anonymous> (/usr/lib/node_modules/forever/node_modules/forever-monitor/lib/index.js:14:19)
Mar 22 11:08:32 Grange MDAH[26962]:     at Module._compile (module.js:409:26)
Mar 22 11:08:32 Grange MDAH[26962]:     at Object.Module._extensions..js (module.js:416:10)
Mar 22 11:08:32 Grange systemd[1]: mydomoathome.service: Main process exited, code=exited, status=1/FAILURE
Mar 22 11:08:32 Grange systemd[1]: mydomoathome.service: Unit entered failed state.
Mar 22 11:08:32 Grange systemd[1]: mydomoathome.service: Failed with result 'exit-code'.
Mar 22 11:08:32 Grange systemd[1]: mydomoathome.service: Service hold-off time over, scheduling restart.
Mar 22 11:08:32 Grange systemd[1]: Stopped MDAH ISS Rest interface for Domoticz to Imperihome.
Mar 22 11:08:32 Grange systemd[1]: Starting MDAH ISS Rest interface for Domoticz to Imperihome...
Mar 22 11:08:32 Grange systemd[1]: Started MDAH ISS Rest interface for Domoticz to Imperihome.
Mar 22 11:08:33 Grange MDAH[26993]: /usr/lib/node_modules/forever/node_modules/forever-monitor/lib/forever-monitor/monitor.js:38
Mar 22 11:08:33 Grange MDAH[26993]:   let execPath = process.execPath;
Mar 22 11:08:33 Grange MDAH[26993]:   ^^^
Mar 22 11:08:33 Grange MDAH[26993]: SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
Mar 22 11:08:33 Grange MDAH[26993]:     at exports.runInThisContext (vm.js:53:16)
Mar 22 11:08:33 Grange MDAH[26993]:     at Module._compile (module.js:373:25)
Mar 22 11:08:33 Grange MDAH[26993]:     at Object.Module._extensions..js (module.js:416:10)
Mar 22 11:08:33 Grange MDAH[26993]:     at Module.load (module.js:343:32)
Mar 22 11:08:33 Grange MDAH[26993]:     at Function.Module._load (module.js:300:12)
Mar 22 11:08:33 Grange MDAH[26993]:     at Module.require (module.js:353:17)
Mar 22 11:08:33 Grange MDAH[26993]:     at require (internal/module.js:12:17)
Mar 22 11:08:33 Grange MDAH[26993]:     at Object.<anonymous> (/usr/lib/node_modules/forever/node_modules/forever-monitor/lib/index.js:14:19)
Mar 22 11:08:33 Grange MDAH[26993]:     at Module._compile (module.js:409:26)
Mar 22 11:08:33 Grange MDAH[26993]:     at Object.Module._extensions..js (module.js:416:10)
Mar 22 11:08:33 Grange systemd[1]: mydomoathome.service: Main process exited, code=exited, status=1/FAILURE
Mar 22 11:08:33 Grange systemd[1]: mydomoathome.service: Unit entered failed state.
Mar 22 11:08:33 Grange systemd[1]: mydomoathome.service: Failed with result 'exit-code'.
Mar 22 11:08:33 Grange systemd[1]: mydomoathome.service: Service hold-off time over, scheduling restart.
Mar 22 11:08:33 Grange systemd[1]: Stopped MDAH ISS Rest interface for Domoticz to Imperihome.
Mar 22 11:08:33 Grange systemd[1]: Starting MDAH ISS Rest interface for Domoticz to Imperihome...
Mar 22 11:08:33 Grange systemd[1]: Started MDAH ISS Rest interface for Domoticz to Imperihome.
Mar 22 11:08:34 Grange MDAH[27022]: /usr/lib/node_modules/forever/node_modules/forever-monitor/lib/forever-monitor/monitor.js:38
Mar 22 11:08:34 Grange MDAH[27022]:   let execPath = process.execPath;
Mar 22 11:08:34 Grange MDAH[27022]:   ^^^
Mar 22 11:08:34 Grange MDAH[27022]: SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
Mar 22 11:08:34 Grange MDAH[27022]:     at exports.runInThisContext (vm.js:53:16)
Mar 22 11:08:34 Grange MDAH[27022]:     at Module._compile (module.js:373:25)
Mar 22 11:08:34 Grange MDAH[27022]:     at Object.Module._extensions..js (module.js:416:10)
Mar 22 11:08:34 Grange MDAH[27022]:     at Module.load (module.js:343:32)
Mar 22 11:08:34 Grange MDAH[27022]:     at Function.Module._load (module.js:300:12)
Mar 22 11:08:34 Grange MDAH[27022]:     at Module.require (module.js:353:17)
Mar 22 11:08:34 Grange MDAH[27022]:     at require (internal/module.js:12:17)
Mar 22 11:08:34 Grange MDAH[27022]:     at Object.<anonymous> (/usr/lib/node_modules/forever/node_modules/forever-monitor/lib/index.js:14:19)
Mar 22 11:08:34 Grange MDAH[27022]:     at Module._compile (module.js:409:26)
Mar 22 11:08:34 Grange MDAH[27022]:     at Object.Module._extensions..js (module.js:416:10)
Mar 22 11:08:34 Grange systemd[1]: mydomoathome.service: Main process exited, code=exited, status=1/FAILURE
Mar 22 11:08:34 Grange systemd[1]: mydomoathome.service: Unit entered failed state.
Mar 22 11:08:34 Grange systemd[1]: mydomoathome.service: Failed with result 'exit-code'.
Mar 22 11:08:34 Grange systemd[1]: mydomoathome.service: Service hold-off time over, scheduling restart.
Mar 22 11:08:34 Grange systemd[1]: Stopped MDAH ISS Rest interface for Domoticz to Imperihome.
Mar 22 11:08:34 Grange systemd[1]: Starting MDAH ISS Rest interface for Domoticz to Imperihome...
Mar 22 11:08:34 Grange systemd[1]: Started MDAH ISS Rest interface for Domoticz to Imperihome.
Mar 22 11:08:35 Grange MDAH[27055]: /usr/lib/node_modules/forever/node_modules/forever-monitor/lib/forever-monitor/monitor.js:38
Mar 22 11:08:35 Grange MDAH[27055]:   let execPath = process.execPath;
Mar 22 11:08:35 Grange MDAH[27055]:   ^^^
Mar 22 11:08:35 Grange MDAH[27055]: SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
Mar 22 11:08:35 Grange MDAH[27055]:     at exports.runInThisContext (vm.js:53:16)
Mar 22 11:08:35 Grange MDAH[27055]:     at Module._compile (module.js:373:25)
Mar 22 11:08:35 Grange MDAH[27055]:     at Object.Module._extensions..js (module.js:416:10)
Mar 22 11:08:35 Grange MDAH[27055]:     at Module.load (module.js:343:32)
Mar 22 11:08:35 Grange MDAH[27055]:     at Function.Module._load (module.js:300:12)
Mar 22 11:08:35 Grange MDAH[27055]:     at Module.require (module.js:353:17)
Mar 22 11:08:35 Grange MDAH[27055]:     at require (internal/module.js:12:17)
Mar 22 11:08:35 Grange MDAH[27055]:     at Object.<anonymous> (/usr/lib/node_modules/forever/node_modules/forever-monitor/lib/index.js:14:19)
Mar 22 11:08:35 Grange MDAH[27055]:     at Module._compile (module.js:409:26)
Mar 22 11:08:35 Grange MDAH[27055]:     at Object.Module._extensions..js (module.js:416:10)
Mar 22 11:08:35 Grange systemd[1]: mydomoathome.service: Main process exited, code=exited, status=1/FAILURE
Mar 22 11:08:35 Grange systemd[1]: mydomoathome.service: Unit entered failed state.
Mar 22 11:08:35 Grange systemd[1]: mydomoathome.service: Failed with result 'exit-code'.
Mar 22 11:08:36 Grange systemd[1]: mydomoathome.service: Service hold-off time over, scheduling restart.
Mar 22 11:08:36 Grange systemd[1]: Stopped MDAH ISS Rest interface for Domoticz to Imperihome.
Mar 22 11:08:36 Grange systemd[1]: Starting MDAH ISS Rest interface for Domoticz to Imperihome...
Mar 22 11:08:36 Grange systemd[1]: Started MDAH ISS Rest interface for Domoticz to Imperihome.
Mar 22 11:08:37 Grange MDAH[27086]: /usr/lib/node_modules/forever/node_modules/forever-monitor/lib/forever-monitor/monitor.js:38
Mar 22 11:08:37 Grange MDAH[27086]:   let execPath = process.execPath;
Mar 22 11:08:37 Grange MDAH[27086]:   ^^^
Mar 22 11:08:37 Grange MDAH[27086]: SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
Mar 22 11:08:37 Grange MDAH[27086]:     at exports.runInThisContext (vm.js:53:16)
Mar 22 11:08:37 Grange MDAH[27086]:     at Module._compile (module.js:373:25)
Mar 22 11:08:37 Grange MDAH[27086]:     at Object.Module._extensions..js (module.js:416:10)
Mar 22 11:08:37 Grange MDAH[27086]:     at Module.load (module.js:343:32)
Mar 22 11:08:37 Grange MDAH[27086]:     at Function.Module._load (module.js:300:12)
Mar 22 11:08:37 Grange MDAH[27086]:     at Module.require (module.js:353:17)
Mar 22 11:08:37 Grange MDAH[27086]:     at require (internal/module.js:12:17)
Mar 22 11:08:37 Grange MDAH[27086]:     at Object.<anonymous> (/usr/lib/node_modules/forever/node_modules/forever-monitor/lib/index.js:14:19)
Mar 22 11:08:37 Grange MDAH[27086]:     at Module._compile (module.js:409:26)
Mar 22 11:08:37 Grange MDAH[27086]:     at Object.Module._extensions..js (module.js:416:10)
Mar 22 11:08:37 Grange systemd[1]: mydomoathome.service: Main process exited, code=exited, status=1/FAILURE
Mar 22 11:08:37 Grange systemd[1]: mydomoathome.service: Unit entered failed state.
Mar 22 11:08:37 Grange systemd[1]: mydomoathome.service: Failed with result 'exit-code'.
Mar 22 11:08:37 Grange systemd[1]: mydomoathome.service: Service hold-off time over, scheduling restart.
Mar 22 11:08:37 Grange systemd[1]: Stopped MDAH ISS Rest interface for Domoticz to Imperihome.
Mar 22 11:08:37 Grange systemd[1]: mydomoathome.service: Start request repeated too quickly.
Mar 22 11:08:37 Grange systemd[1]: Failed to start MDAH ISS Rest interface for Domoticz to Imperihome.
Mar 22 11:08:37 Grange systemd[1]: mydomoathome.service: Unit entered failed state.
Mar 22 11:08:37 Grange systemd[1]: mydomoathome.service: Failed with result 'start-limit-hit'.

Merci

**Comment by empierre** [comment]
Hello,

  Il me faut ces infos pour te répondre:

cat /etc/os-release
node -v
npm -v

**Comment by tomagoshy23** [comment]
Bonjour,

root@Grange:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
root@Grange:~# node -v
v4.9.1
root@Grange:~# npm -v
2.15.12

**Comment by empierre** [comment]
essayes ceci:

apt-cache  policy nodejs

et de monter de version de nodejs vers la version 8, ta version npm est en
décalage (plus récente)

**Comment by tomagoshy23** [comment]
Merci beaucoup !
Cela fonctionne. avec la version 8.

**Comment by tomagoshy23** [comment]
nodejs --version
v8.17.0
npm --version
6.13.4
