### ISSUE TITLE
MyDomoAtHome not working with newest Node.js and NPM

### ISSUE THREAD

**Issue by Kouwe-sudo** [empierre/MyDomoAtHome#193]
Due to a necessary update of Node-red on my Raspberry Pi 3+B I also had to switch to newer versions of Node.js and NPM:

$ npm --version  6.14.7
$ node --version v12.18.3

 However, one consequence is that the nice application of your 'MyDomoAtHome' doesn't work anymore. I get the following message when reinstalling:

'The following packages have unfulfilled requirements:
 mydomoathome : Requirements: npm (>= 3.5.2)
E: Cannot fix problems, you are holding faulty packets.'

How can I fix this? I have even looked at the French site of the Domoticz forum but the solution is not there yet. 

By the way, I did find that nowadays you have to use 'deb https://www.e-nef.com/domoticz/mdah/ buster contrib' instead of the 
' deb https://www.e-nef.com/domoticz/mdah/ /' 

Is it perhaps an idea to change that in github?

**Comment by empierre** [comment]
Hello,

  Two issues that I can't fix now, both known and already reported

  - repo management: yes second is the one working, still don't know why
only one and not two

  - npm version: clearly an issue with debian packaging, why ? I still
don't know but uploading the .deb package there
https://www.e-nef.com/domoticz/mdah/  and installing manually is fine.

**Comment by Kouwe-sudo** [comment]
Thanks for the swift reply, but I don’t understand what you are saying. I hope you don’t get upset by that. Do you mean I can add a second npm manually for your application. And which version should I use then?

> - repo management: yes second is the one working, still don't know why
> only one and not two??
> 
> - npm version: clearly an issue with debian packaging, why ? I still
> don't know but uploading the .deb package there
> https://www.e-nef.com/domoticz/mdah/ and installing manually is fine.??


> Op 29 jul. 2020 om 15:17 heeft Emmanuel <notifications@github.com> het volgende geschreven:
> 
> ﻿
> Hello,
> 
> Two issues that I can't fix now, both known and already reported
> 
> - repo management: yes second is the one working, still don't know why
> only one and not two
> 
> - npm version: clearly an issue with debian packaging, why ? I still
> don't know but uploading the .deb package there
> https://www.e-nef.com/domoticz/mdah/ and installing manually is fine.
>

**Comment by empierre** [comment]
Hello,

  no just download this one:

https://www.e-nef.com/domoticz/mdah/node-mydomoathome-0.2.42.deb

  and do a dkpg -i node-mydomoathome-0.2.42.deb

so your package manager will be quiet afterward, there is no npm dependency
on it.

**Comment by Kouwe-sudo** [comment]
Emmanuel,

Thank you very much for the explanation. I didn’t expect to have Emperihome up and running so fast but it runs like a charm again. 
Thank you for your time and of course MyDomoAtHome

> Op 29 jul. 2020 om 16:13 heeft Emmanuel <notifications@github.com> het volgende geschreven:
> 
> ﻿
> Hello,
> 
> no just download this one:
> 
> https://www.e-nef.com/domoticz/mdah/node-mydomoathome-0.2.42.deb
> 
> and do a dkpg -i node-mydomoathome-0.2.42.deb
> 
> so your package manager will be quiet afterward, there is no npm dependency
> on it.
> 
> 
>

**Comment by empierre** [comment]
welcome !
