### ISSUE TITLE
Not found after sudo apt-get update

### ISSUE THREAD

**Issue by mvzut** [empierre/MyDomoAtHome#195]
I wanted to reinstall mdah on my Raspberry Pi, because I somehow broke it with modifications to my nodejs. But when doing a "sudo apt-get update", I get a "404 Not Found" error for mdah:
`pi@Domoticz:~ $ sudo apt-get update`
`Get:1 http://archive.raspberrypi.org/debian stretch InRelease [25.4 kB]`
`Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease`
`Hit:3 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease`
`Hit:4 https://repo.mosquitto.org/debian stretch InRelease`
`Ign:5 https://www.e-nef.com/domoticz/mdah  InRelease`
`Err:6 https://www.e-nef.com/domoticz/mdah  Release`
` 404  Not Found [IP: 2001:41d0:301::23 443]`
`Hit:7 https://deb.nodesource.com/node_14.x buster InRelease`
`Reading package lists... Done`
`E: The repository 'https://www.e-nef.com/domoticz/mdah  Release' does not have a Release file.`
`N: Updating from such a repository can't be done securely, and is therefore disabled by default.`
`N: See apt-secure(8) manpage for repository creation and user configuration details.`

I did add the key (again) just to be sure, but that didn't help. I can access the package from my Pi, since
`wget http://www.e-nef.com/domoticz/mdah/node-mydomoathome-latest.deb `
works just fine.
I then did a
`sudo dpkg -i node-mydomoathome-latest.deb`
which installed mdah and restored functionality.

Two questions:
1. What could have caused the 404 not found error?
2. Is it ok to install mdah using the dpkg method, or is this not advised?

Thanks for any advice.

**Comment by empierre** [comment]
Hello, 

  The repo is not that stable since I tried to make a package specific with buster...

**Comment by mvzut** [comment]
Sorry I don't know exactly what you mean with that empierre. Is the manual installation method not stable? And am I the only one getting the 404 errors? Can't imagine what I'm doing wrong, it worked in the past.
