### ISSUE TITLE
Debian repository at https://www.e-nef.com/domoticz/mdah is broken

### ISSUE THREAD

**Issue by akliouev** [empierre/MyDomoAtHome#196]
under Ubuntu (18.04.4 LTS and 20.04.1 LTS) adding the repository as per the instructions (adding "deb https://www.e-nef.com/domoticz/mdah/ /" to /etc/apt/sources.list) breaks apt
with this line in the sources.list "apt-get update" fails and reports "E: The repository 'https://www.e-nef.com/domoticz/mdah  Release' does not have a Release file."

Please advise

**Comment by empierre** [comment]
can you modify to this and confirm it is ok ? 
deb https://www.e-nef.com/domoticz/mdah/ buster contrib

**Comment by albebert** [comment]
Ko for me too 

`root@mydomoathome:~# apt update

Hit:1 http://ftp.debian.org/debian buster InRelease

Hit:2 http://security.debian.org buster/updates InRelease

Hit:3 http://ftp.debian.org/debian buster-updates InRelease

Get:4 https://www.e-nef.com/domoticz/mdah buster InRelease [2881 B]

Fetched 2881 B in 0s (7601 B/s)

Reading package lists... Done

Building dependency tree

Reading state information... Done

All packages are up to date.

root@mydomoathome:~# apt install MyDomoAtHome

Reading package lists... Done

Building dependency tree

Reading state information... Done

E: Unable to locate package MyDomoAtHome
`

so i get directly the .deb from repo and install it, bit require sudo. 

npm WARN npm npm does not support Node.js v10.24.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
/var/lib/dpkg/tmp.ci/preinst: line 18: sudo: command not found

i don't use sudo on my machine (btw installed for this, but i think that the script can check if it run with a privilegied user)

**Comment by empierre** [comment]
@albebert there are two points here:
- first repo, for me it works on a Buster, but it seems you are not on it
- the sudo, but it seems you have a modified distro, checking to see if sudo can be removed

**Comment by albebert** [comment]
i use standard debian 10 LXC container on proxmox. 

Can test on fresh Debian VM, but i d'ont use sudo (during installation if you provide a root password, debian don't install sudo, it does only if you don't provide a root password) 

planed to test tonight (french time)

**Comment by empierre** [comment]
should be fixed
