### ISSUE TITLE
Problem with some devices

### ISSUE THREAD

**Issue by drabo32** [empierre/MyDomoAtHome#267]
Hello
Since last month, I don't have every devices from Domoticz

So, with Imperihome I lost all switches for exemple.
Strangely, I have temp or scene...

What can I do to repare...

Thank's

**Comment by drabo32** [comment]
Sorry I found the solution

It was because there's un default user witch haven't all the permission
The question is : why and where's this default user ?

**Comment by empierre** [comment]
ok, so the change in Domoticz is impacting MDAH...

try the config.json  with the "auth": { "username": "admin", "password":
"admin" },   (change to your informations)

see https://github.com/empierre/MyDomoAtHome
