### ISSUE TITLE
Cannot start on Debian 7 (OpenMediaVault)

### ISSUE THREAD

**Issue by Condorello** [empierre/MyDomoAtHome#29]
Hello, i cannot start the daemon after following the wiki on Domoticz site. Bellow the output of my shell, thanks in advance for your help!

root@NAS:/opt/domoticz/MyDomoAtHome# /usr/bin/plackup -E production -s Starman --workers=4 -p 8078 -a /opt/domoticz/MyDomoAtHome/bin/app.pl --pid /tmp/mydomoathome.pid
Error while loading /opt/domoticz/MyDomoAtHome/bin/app.pl: Unable to parse the configuration file: /opt/domoticz/MyDomoAtHome/config.yml: YAML Error: Couldn't parse single line value
   Code: YAML_PARSE_ERR_SINGLE_LINE
   Line: 12
   Document: 1
 at /usr/share/perl5/YAML/Loader.pm line 148
 at /usr/share/perl5/Dancer/Config.pm line 202
        Dancer::Config::load_settings_from_yaml('/opt/domoticz/MyDomoAtHome/config.yml') called at /usr/share/perl5/Dancer/Config.pm line 176
        Dancer::Config::load('Dancer::Config') called at /usr/share/perl5/Dancer.pm line 258
        Dancer::import('Dancer') called at /opt/domoticz/MyDomoAtHome/bin/app.pl line 2
        Plack::Sandbox::_2fopt_2fdomoticz_2fMyDomoAtHome_2fbin_2fapp_2epl::BEGIN() called at /opt/domoticz/MyDomoAtHome/bin/app.pl line 2
        eval {...} called at /opt/domoticz/MyDomoAtHome/bin/app.pl line 2
        require /opt/domoticz/MyDomoAtHome/bin/app.pl called at (eval 5) line 3
        eval 'package Plack::Sandbox::_2fopt_2fdomoticz_2fMyDomoAtHome_2fbin_2fapp_2epl;
{
    my $app = do $_file;
    if ( !$app && ( my $error = $@ || $! )) { die $error; }
    $app;
}

;' called at /usr/share/perl5/Plack/Util.pm line 118
        Plack::Util::_load_sandbox('/opt/domoticz/MyDomoAtHome/bin/app.pl') called at /usr/share/perl5/Plack/Util.pm line 155
        Plack::Util::load_psgi('/opt/domoticz/MyDomoAtHome/bin/app.pl') called at /usr/share/perl5/Plack/Runner.pm line 176
        Plack::Runner::__ANON__() called at /usr/share/perl5/Plack/Runner.pm line 23
        Plack::Runner::__ANON__() called at /usr/share/perl5/Plack/Loader.pm line 59
        Plack::Loader::preload_app('Plack::Loader=HASH(0x25c78e0)', 'CODE(0x25ec500)') called at /usr/share/perl5/Plack/Runner.pm line 260
        Plack::Runner::run('Plack::Runner=HASH(0x23c1688)') called at /usr/bin/plackup line 10
BEGIN failed--compilation aborted at /opt/domoticz/MyDomoAtHome/bin/app.pl line 2.
root@NAS:/opt/domoticz/MyDomoAtHome#

**Comment by empierre** [comment]
This is your config.yml that has a parsing issue:
"YAML Error: Couldn't parse single line value
Code: YAML_PARSE_ERR_SINGLE_LINE
Line: 12
Document: 1"

**Comment by Condorello** [comment]
I have only changed the ip/port, tris is the cat:

root@NAS:/opt/domoticz/MyDomoAtHome# cat config.yml
# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

#MyDomoAtHome specific configuration
domo_path: "http://192.168.99.1:8077"
external_url_camera : "http://ip:port/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=&pwd="
volumio_path: ""  #Just the IP here assuming default port and no login/password, if void inactive


# Your application's name
appname: "MyDomoAtHome"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: UTF-8
engines:
    serializer:
        JSON:
            utf8: 0
serializer: 'JSON'
#template: "simple"

**Comment by empierre** [comment]
try removing your file, do a cp again and modify ip/port and try starting it with start2.sh to test

**Comment by Condorello** [comment]
Thanks for your help, i tried as you suggest but still got the same error on line 12:


root@NAS:/opt/domoticz/MyDomoAtHome# ./start2.sh
Error while loading bin/app.pl: Unable to parse the configuration file: /opt/domoticz/MyDomoAtHome/config.yml: YAML Error: Couldn't parse single line value
   Code: YAML_PARSE_ERR_SINGLE_LINE
   Line: 12
   Document: 1
 at /usr/share/perl5/YAML/Loader.pm line 148
 at /usr/share/perl5/Dancer/Config.pm line 202
	Dancer::Config::load_settings_from_yaml('/opt/domoticz/MyDomoAtHome/config.yml') called at /usr/share/perl5/Dancer/Config.pm line 176
	Dancer::Config::load('Dancer::Config') called at /usr/share/perl5/Dancer.pm line 258
	Dancer::import('Dancer') called at bin/app.pl line 2
	Plack::Sandbox::bin_2fapp_2epl::BEGIN() called at bin/app.pl line 2
	eval {...} called at bin/app.pl line 2
	require bin/app.pl called at (eval 5) line 3
	eval 'package Plack::Sandbox::bin_2fapp_2epl;
{
    my $app = do $_file;
    if ( !$app && ( my $error = $@ || $! )) { die $error; }
    $app;
}

;' called at /usr/share/perl5/Plack/Util.pm line 118
	Plack::Util::_load_sandbox('bin/app.pl') called at /usr/share/perl5/Plack/Util.pm line 155
	Plack::Util::load_psgi('bin/app.pl') called at /usr/share/perl5/Plack/Runner.pm line 176
	Plack::Runner::__ANON__() called at /usr/share/perl5/Plack/Runner.pm line 23
	Plack::Runner::__ANON__() called at /usr/share/perl5/Plack/Loader.pm line 59
	Plack::Loader::preload_app('Plack::Loader=HASH(0x1ad5730)', 'CODE(0x1b034a8)') called at /usr/share/perl5/Plack/Runner.pm line 260
	Plack::Runner::run('Plack::Runner=HASH(0x18d85f8)') called at /usr/bin/plackup line 10
BEGIN failed--compilation aborted at bin/app.pl line 2.

**Comment by empierre** [comment]
try replacing all double quotes by single quotes and tell me

**Comment by Condorello** [comment]
Exactly the same output as with “

**Comment by empierre** [comment]
this is weird... I did search for this message, it is usually about more than a value presented to the parser (which expects a unique key:value scheme per line)

can you see if there are return lines missing, something that could explain this ?

**Comment by Condorello** [comment]
The line is this (with ‘ or “ it’s the same):

# Your application's name
appname: ‘MyDomoAtHome'

**Comment by empierre** [comment]
it is the same, just safer if double quotes are within

**Comment by empierre** [comment]
an idea, move to the line below this:
#Just the IP here assuming default port and no login/password, if void inactive

**Comment by Condorello** [comment]
It changed the line of the error but still getting the same output:

Error while loading bin/app.pl: Unable to parse the configuration file: /opt/domoticz/MyDomoAtHome/config.yml: YAML Error: Couldn't parse single line value
   Code: YAML_PARSE_ERR_SINGLE_LINE
   Line: 9
   Document: 1

It’s very strange, it’s currently a single line value!!!

**Comment by empierre** [comment]
so let's regress, try a minimal conf to see:
domo_path: "http://192.168.99.1:8077"
appname: "MyDomoAtHome"
layout: "main"

**Comment by Condorello** [comment]
root@NAS:/opt/domoticz/MyDomoAtHome# ./start2.sh 
log directory /opt/domoticz/MyDomoAtHome/bin/.. isn't writable/executable and can't chmod it at /usr/share/perl5/Dancer/Logger.pm line 16
log directory /opt/domoticz/MyDomoAtHome/bin/.. isn't writable/executable and can't chmod it at /usr/share/perl5/Dancer/Logger.pm line 16
2015/09/10-13:51:05 Starman::Server (type Net::Server::PreFork) starting! pid(9437)
Resolved [*]:3001 to [::]:3001, IPv6
Not including resolved host [0.0.0.0] IPv4 because it will be handled by [::] IPv6
Binding to TCP port 3001 on host :: with IPv6
Setting gid to "33 33 33"

**Comment by empierre** [comment]
ok so it is good.

let's reintroduce first :+
external_url_camera : "http://ip:port/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=&pwd=" volumio_path: ""


and if still ok:
charset:
 UTF-8 engines: 
   serializer: JSON: 
      utf8: 0 
serializer: 'JSON'

**Comment by Condorello** [comment]
It works (with a comment on a duplicate string). I can rename that start2.sh to start.sh or we have other debugging to do?


root@NAS:/opt/domoticz/MyDomoAtHome# ./start2.sh 
log directory /opt/domoticz/MyDomoAtHome/bin/.. isn't writable/executable and can't chmod it at /usr/share/perl5/Dancer/Logger.pm line 16
log directory /opt/domoticz/MyDomoAtHome/bin/.. isn't writable/executable and can't chmod it at /usr/share/perl5/Dancer/Logger.pm line 16
2015/09/10-19:51:23 Starman::Server (type Net::Server::PreFork) starting! pid(20651)
Resolved [*]:3001 to [::]:3001, IPv6
Not including resolved host [0.0.0.0] IPv4 because it will be handled by [::] IPv6
Binding to TCP port 3001 on host :: with IPv6
Setting gid to "33 33 33"









root@NAS:/opt/domoticz/MyDomoAtHome# cat config.yml
domo_path: "http://192.168.99.1:8077"
appname: "MyDomoAtHome"
layout: "main"
external_url_camera: "http://ip:port/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=&pwd="
volumio_path: ""
charset: UTF-8 
engines:
#serializer:
#JSON:
utf8: 0
serializer: 'JSON'

**Comment by empierre** [comment]
looks fine, why did you comment out 
#serializer: #JSON:   ?

now I recommend using run_once.sh after configuring MyDomoAtHome.sh

start2.sh is a mono process for debugging, start.sh is now deprecated.

**Comment by Condorello** [comment]
> why did you comment out 
> #serializer: #JSON: ?
> 
I have a doubled "serialized" and perl report an alert. Finally it works fine, and it's a great gateway for imperihome! Trans for your work with this program and for your kind help.

Andrea

**Comment by empierre** [comment]
I'm trying now to install OMV on a odroid XU4 for I was planning top do so and installing manually OMV is painfull if not impossible... so I'll have time to see that. 

any recommendation on OMV ?

**Comment by Condorello** [comment]
Mmm... Any particular advice, i have an amd e350 up and running since 2-3 year 24h/24 witch run tvheadend, plex, domoticz, asterisk, openvpn and storage with 3 disk and before also one virtualbox machine. It's a perfect distro for a home-server once configured!

**Comment by empierre** [comment]
Hello,

  thanks for the info. 

  can you tell me if your accents are correctly decoded this way ? (if you have accentuated caracters of course !)
