### ISSUE TITLE
energy devices value change in domoticz

### ISSUE THREAD

**Issue by empierre** [empierre/MyDomoAtHome#32]
"I confirm this: energy devices aren not visible anymore since latest Domoticz version (V2.3072) and/or MyDomoAtHome update. The interface (IP:3001/devices) lists the devices with value="unk" but are not visible (not found) in Imperihome."

**Comment by Alomamabobo** [comment]
Same here :)

**Comment by empierre** [comment]
changed, bith behavior managed.
