### ISSUE TITLE
support for squeezebox

### ISSUE THREAD

**Issue by empierre** [empierre/MyDomoAtHome#39]

**Comment by CondormanFr** [comment]
Je confirme : UNK Sw Squeezebox Radio

**Comment by empierre** [comment]
que te donnes ceci:
/json.htm?type=devices&filter=all&used=true&order=Name

**Comment by CondormanFr** [comment]
```
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "",
Description: "",
Favorite: 1,
HardwareID: 3,
HardwareName: "MediaServer",
HardwareType: "Logitech Media Server",
HardwareTypeVal: 60,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "0000001",
Image: "Light",
IsSubDevice: false,
LastUpdate: "2016-03-14 20:31:09",
Level: 0,
LevelInt: 0,
MaxDimLevel: 15,
Name: "Squeezebox Radio",
Notifications: "false",
PlanID: "6",
PlanIDs: [
6
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Off",
StrParam1: "",
StrParam2: "",
SubType: "AC",
SwitchType: "Media Player",
SwitchTypeVal: 17,
Timers: "false",
Type: "Lighting 2",
TypeImg: "LogitechMediaServer",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "1478",
YOffset: "569",
idx: "82"
},
```

**Comment by empierre** [comment]
là c'est au repos, tu aurais un moyen de me donner cela avec les valeurs retournées d'une part, et d'autre part l'url appelée par domoticz quand tu fais les actions dans l'IHM spécifique ? 

je n'ai pas moyen de reproduire cela et ce n'est pas documenté...

**Comment by CondormanFr** [comment]
Là, ca va être plus compliqué car c'est dans la chambre et madame dort... J'essaierai de faire ça à un autre moment ... ;-)

**Comment by empierre** [comment]
voui ;-)

**Comment by empierre** [comment]
j'ai regardé, squeeze/kodi sont supportés directement depuis Imperihome, par contre je n'ai rien dans l'ISS d'IH...

**Comment by CondormanFr** [comment]
Kodi est supporté mais pas les squeezebox à priori. Enfin je n'ai pas vu sinon.

**Comment by empierre** [comment]
jr suis en beta,  a voir.

par contre rien dans iss a part faire un multiswich mais rien pour
selectionner la musique en vue
