### ISSUE TITLE
Adding camera stream in imperihome

### ISSUE THREAD

**Issue by eltanio** [empierre/MyDomoAtHome#41]
Hi, and first, thanks for your job!

I have a problem to get a video stream in imperihome.
When I create my camera in domoticz, I can test it on my laptop accessing domoticz via 8080 port.
I can see a camera in imperihome, but nothing appears.
Do I have to configure the external_url_camera in config.yml? or put a # to comment it?
And if I have to configure it, I have to keep the syntax, or I put my external access to my camera stream?
I hope I've been clear (sorry, I'm from France)

Thanks in advance,
Antoine

**Comment by empierre** [comment]
Bonjour Antoine,

  Je pense que je vais supprimer le support des caméras car il semble que
le format exporté par Domoticz ne fonctionne pas dans Imperihome.

  Imperihome propose de gérer nativement les caméras ce qui est beaucoup
mieux ainsi

**Comment by eltanio** [comment]
Re-bonjour,

et moi qui écrivait en anglais...
J'ai cherché dans imperihome, mais je trouve pas comment afficher la caméra.
Doit-on renseigner l'url dans le fichier config.yml, ou tout se fait via imperihome?

Merci

**Comment by empierre** [comment]
les deux sont possible:
- une camera IP peut être ajoutée directement comme ISS dans ImperiHome
- je n'ai pas vérifié quel format vidéo accesptait en mode ISS Imperihome,
j'ai juste proposé de rajouter une URL externe, ce que ne propose pas
domoticz

2015-10-19 16:06 GMT+02:00 eltanio <notifications@github.com>:

**Comment by eltanio** [comment]
ah oui effectivement maintenant ça marche et c'est aussi simple!
Merci pour ces réponses rapides!

Antoine
