### ISSUE TITLE
Probleme de mise à jour

### ISSUE THREAD

**Issue by eltanio** [empierre/MyDomoAtHome#42]
Bonjour!

J'ai téléchargé la dernière version de MyDomoAtHome.
Pour le lancer j'ai ajouté start2.sh en tant que service au démarrage, mais cela ne fonctionne pas.

Quand je lance sudo service start2.sh reload, il me met une erreur 

Error while loading /domoticz/MyDomoAtHome/bin/app.pl: Can't locate Time/Moment.pm in @INC (@INC contains: /domoticz/MyDomoAtHome/bin/../lib /domoticz/MyDomoAtHome/lib /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at /domoticz/MyDomoAtHome/lib/Domo.pm line 31.
BEGIN failed--compilation aborted at /domoticz/MyDomoAtHome/lib/Domo.pm line 31.
Compilation failed in require at /domoticz/MyDomoAtHome/bin/app.pl line 20.
BEGIN failed--compilation aborted at /domoticz/MyDomoAtHome/bin/app.pl line 20.

Sinon, j'ai aussi constaté qu'il n'y avait pas le fichier MyDomoAtHome.sh indiqué dans la procédure d'install (mais c'est peut-être normal)

Encore merci!

**Comment by empierre** [comment]
Hello,

  I answer in English for this has a bit of impact... 

  For 3 days a weird merge has removed two files needed on first installation.

  So please go a git pull to retrive the missing files and modifi MyDomoAtHome.sh and then run ./run-once.sh to install missing libraries
