### ISSUE TITLE
pidfile is not being removed at mdh stop

### ISSUE THREAD

**Issue by lrybak** [empierre/MyDomoAtHome#46]
I'm using attached start/stop script MyDomoAtHome.sh

I made some workaround which is working for me
if [ "$SIGNAL" = "KILL" ] || [ "$SIGNAL" = "TERM" ]; then
rm -f "$PIDFILE"
fi

**Comment by empierre** [comment]
ok just committed, can you test ?

**Comment by lrybak** [comment]
Sorry for delay. Yes it works good now. 
BTW. Thanks dude for very good piece of code!
