### ISSUE TITLE
Fibaro Dimmer 2 flickering in ImperiHome

### ISSUE THREAD

**Issue by MAkerboom** [empierre/MyDomoAtHome#48]
Light is just ON, but is displayed flickering in ImperiHome. Switching the light works, but doesn't fix the issue: https://youtu.be/bjgcEOibqFc

**Comment by empierre** [comment]
Hello,

 is this a push on button ? if yes this is normal

**Comment by MAkerboom** [comment]
No, no actions... light is just ON but not displayed this way.

**Comment by empierre** [comment]
imperihome does not handle it fine as it does not exist; it is always on when you push, the gateways sends an on to domoticz, but imperihome moves it to off on the UI, and when it refreshes it get a on status again.

**Comment by MAkerboom** [comment]
Why does imperihome move it to OFF? Should I report it? 

As MDAH is a kind of 'proxy', could it be fixed on the MDAH-side?

**Comment by empierre** [comment]
I asked for a push device, but I dont' know how far it is in their roadmap, so you can try too.

the proxy will not change the UI side, would you like a push on button becoming either green or red on pushing it ?not sure and many people would complain there...

**Comment by MAkerboom** [comment]
I don't think I truly understand... domoticz does know the correct on or off state... why can't it be supplied to imperihome as-is?

**Comment by empierre** [comment]
too much logic on the UI... but domoticz has the same issue sometimes, RGB lamps can't be used at this time because of a wrong model of data in domoticz...

**Comment by MAkerboom** [comment]
so it's really a domoticz issue because it solves the push on button logic in the UI?

(if that's not the case, just leave it.. I think I'm just not going to grasp. Thanks for answering all my questions :+1: )

**Comment by empierre** [comment]
for RGB yes, for push on no ;-)

**Comment by empierre** [comment]
Update: new beta from imperihome has the pulsable for switch, I guess we'll be able to have it very soon in the official version so I'll see how it works !

**Comment by MAkerboom** [comment]
Can't wait... Keep me posted!

Op di 10 nov. 2015 13:00 schreef Emmanuel <notifications@github.com>:

**Comment by MAkerboom** [comment]
It's working now for me, great!
