### ISSUE TITLE
Access Imperihome from Internet

### ISSUE THREAD

**Issue by bdormael** [empierre/MyDomoAtHome#5]
Dear,

Since the thread in Domoticz is locked, I'm requesting help via here:

I have Domoticz, MyDomo running on my Raspberry and I can connect via the Imperihome App to the Gateway as long as I stay in my own Wifi Network.

I've configured port forwarding on my router to open port 5001, but when I fill in my external IP address in my browser or app with the 5001 port, it is not working anymore.
Am I missing something ?
Am I forced to install that proxy server which is also explained or can I do it without it ?

**Comment by empierre** [comment]
Hello,

  a new thread has been opened: http://domoticz.com/forum/viewtopic.php?f=31&t=6619&p=43787&hilit=imperihome#p43787

  Proxy is not an obligation, but a best practice to protect your applications, domoticz and MyDomoAtHome. 

  That said, do you access from your smartphone domoticz in https ? when you do that are you disconnected from your wifi ? 

  Also remember that port forwarding works for a port and an IP, so have you set your internal IP right ? remember to restart your router and check configuration has been saved.

**Comment by bdormael** [comment]
Hi,

Domoticz is access on my Smartphone via HTTP (bdormael.synology.me:8080) when I'm on the road via 3G
MyDomo is configured on port 5001 and in my router I've setup portforwarding to that port and to the local IP of my Raspberry where MyDomo is installed (just like I did for Domoticz port 8080) and the router has been restarted.

The config files in MyDomo (Production.yml, Config.yml & Development.yml) all have the Raspberry internal ip address configured and the Domoticz Port which is running on the same Raspberry.
I tried to enter the external Domoticz address (bdormael.synology.me:8080) as well in the config files, but then MyDomo won't start.

When working via wifi at home, all is fine via the Imperihome app where I've both configured the internal as external address, when turning off WIFI and 3G jumps in, I cannot connect anymore.

Imperihome is just trying to refresh continiously, I also tried the external address via Chrome browser on my PC but it timesout after 30 seconds, I don't get the setup page from MyDomo

**Comment by empierre** [comment]
oops... forum communication is not great as it seems... new thread elsewhere: http://domoticz.com/forum/viewtopic.php?f=21&t=6882

Imperihome does try to refresh quite agressively this is normal. 

Switching from wifi to 3G with an access issue means either a Imperihome client issue or a router issue, 

do you have a basic auth setup somewhere ? do you use HTTP or HTTPS in your URL ? 

would it be possible to call from 3G the http://bdormael.synology.me:5001/ and see what you have ? no need to use the imperihome client if this step fails.

**Comment by bdormael** [comment]
http://bdormael.synology.me:5001/  fails via 3G (after 1 minute I get following error in chrome on Android : ERR_CONNECTION_TIMED_OUT)

I use HTTP in my URL, not HTTPS (also for Domoticz)

In Domoticz, I use basic authentication (popup) when used externally

**Comment by empierre** [comment]
and if you do a netstat -ta do you see any external connexion on your rpi ?

the best would be lsof if you know it.

**Comment by bdormael** [comment]
I'll test when I'm home (am at work now), but yesterday I did a ping from my rpi to an external address, and that works fine, also my Domoticz is running on the same rpi, and that I can access externally

**Comment by bdormael** [comment]
Just another question:
- In my config files (config.yml, production.yml & deveopler.yml), I need to keep the local ip addresses to my Domoticz server ?

- If using basic authentication in Domoticz for external usage, do I need to specify that somewhere in MyDomo ?

**Comment by bdormael** [comment]
I just noticed in my Domoticz settings that I'm using a "Login Page" as authentication, not "Basic Authentication", will that make a difference ?

**Comment by empierre** [comment]
try also changing the 5001 to another value (in start2.sh or startup script
and *.yml

**Comment by bdormael** [comment]
Yeah, I tried changing ports as well wherever 5001 was mentioned I changed to 52226 and changed portforwarding too in the router, same issue I'm afraid

**Comment by empierre** [comment]
can you start an apache on let's say 52226 port and see if you can reach it
with port forwarding ?

**Comment by bdormael** [comment]
Hi,

I have restored a backup of my rpi from my SD Card image, then installed MyDomo again, and now I can access Imperihome from the internet, very weird.
I have no clue what the change was, but it's ok now.

Thank you very much for your support and sorry for the inconvenience.

Much appreciated
