### ISSUE TITLE
NodeJS | mdah.json not in /home/pi but /etc

### ISSUE THREAD

**Issue by pepijng** [empierre/MyDomoAtHome#53]
It would be preferable to relocate the mdah.json file. /home/pi do not exist on non Raspberry Pi systems :)

**Comment by empierre** [comment]
Hello,

  Where did you see this ? the target installation will be with a .deb package so it would be in its own directory, and thus independant from the distro (not for everything sadly...)

**Comment by empierre** [comment]
Hello,

  closing since the now tagret is very different, packages still beta but some are working now

http://e-nef.com/domoticz/mdah/

**Comment by empierre** [comment]
closed
