### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by CondormanFr** [empierre/MyDomoAtHome#54]
Hello,
I tried to build the dockerfile but I get an error :  

``
Step 15 : RUN cd MyDomoAtHome && carton install --deployment
 ---> Running in 32b837c62eb7
[91mCan't locate cpanfile: (cpanfile)
[0mRemoving intermediate container 32b837c62eb7
The command '/bin/sh -c cd MyDomoAtHome && carton install --deployment' returned a non-zero code: 255
``

Is there any already docker file working ?
Thanks

**Comment by empierre** [comment]
Hello,

  I've not rebuilt it recently as I am rewriting everything in nodeJS (only status, no actuator yet) here: https://github.com/empierre/MyDomoAtHome/tree/nodejs

  What platform are you using ?

**Comment by CondormanFr** [comment]
Hi,

I don’t see the tree/nodejs folder on github.

I’m using docker on a synology 1515+ box (Intel proc).

Regards

Romain
I’m french

**Comment by empierre** [comment]
bonjour Romain, 

  Je t'ai mis le lien ci-dessus.

  Je pense faire une IHM justement pour les utilisateurs de syno intel ou non, car sinon même avec un docker ce sera un peu compliqué...

**Comment by CondormanFr** [comment]
Vu. Je vais attendre alors.

**Comment by empierre** [comment]
bonjour,

  image docker corrigée... mais non testée...

**Comment by CondormanFr** [comment]
Merci. En revanche, quand je la lance, j'ai cette erreur :  
```
BEGIN failed--compilation aborted at /root/MyDomoAtHome/bin/app.pl line 19.
Error while loading /root/MyDomoAtHome/bin/app.pl: Can't locate Dancer.pm in @INC (you may need to install the Dancer module) (@INC contains: /root/MyDomoAtHome/local/lib/perl5/x86_64-linux /root/MyDomoAtHome/local/lib/perl5 /usr/local/lib/perl5/site_perl/5.22.1/x86_64-linux /usr/local/lib/perl5/site_perl/5.22.1 /usr/local/lib/perl5/5.22.1/x86_64-linux /usr/local/lib/perl5/5.22.1 .) at /root/MyDomoAtHome/bin/app.pl line 19.

```

**Comment by empierre** [comment]
version docker nodejs fonctionne ! à tester
