### ISSUE TITLE
add planID management for rooms

### ISSUE THREAD

**Issue by empierre** [empierre/MyDomoAtHome#57]
http://192.168.0.28:8080/json.htm?type=plans&order=name&used=true

**Comment by empierre** [comment]
I propose to use planID if >0 and normal in the other case

**Comment by CondormanFr** [comment]
Good idea

**Comment by empierre** [comment]
the issue I may have or not would be to have it in both (switches/utilitities/...) and Plans, I don't know what is best following usage.

I've seen that in planID you can have a device in several ones, is that a use ?

**Comment by CondormanFr** [comment]
Yes  a device can be added to several plans; Perhaps you can add  "virtual" room to keep your switches/utilitities/... entries grouped together.

**Comment by empierre** [comment]
Proposal:
         "PlanID" : "0" => use existing Domoticz categories
          else place it in a room holding the name for each PlanID
 Limitation: a device cannot be in two rooms in IH, so if there is e.g. "PlanIDs" : [ 3, 4 ] only "PlanID" : "3" decalred by DZ will be taken into account

**Comment by MarcusKlerks** [comment]
I have no experience with rooms in IH but I agree with the proposal if and only if it still remains possible to create one or more "dashboard" pages that hold selected (favorite) devices,

**Comment by jonferreira** [comment]
rooms is only used by IH in List View, it has no effect on Dashboard :-)

**Comment by empierre** [comment]
Yes !

**Comment by empierre** [comment]
hardening done, BIG thanks @jonferreira
