### ISSUE TITLE
Stop button Hasta blinds

### ISSUE THREAD

**Issue by justintime1976** [empierre/MyDomoAtHome#6]
There is no stop button visible with device "Rollertrol Hasta new"

**Comment by empierre** [comment]
Confirmed working on venitian blinds EU

**Comment by justintime1976** [comment]
Sorry, but the issue is still there??

**Comment by empierre** [comment]
oops, wrong user reporting ok thus... sorry

**Comment by empierre** [comment]
did you send me your database to I could test ?

(note for myself:
*stopable 0/1)*

**Comment by justintime1976** [comment]
Hi Emmanuel,

 

I have sent the backup wit hit.

 

Its the devicename “Zonnescherm!”

 

Justin

 

Van: Emmanuel [mailto:notifications@github.com] 
Verzonden: maandag 7 september 2015 13:15
Aan: empierre/MyDomoAtHome <MyDomoAtHome@noreply.github.com>
CC: justintime1976 <jlcornelius76@gmail.com>
Onderwerp: Re: [MyDomoAtHome] Stop button Hasta blinds (#6)

 

did you send me your database to I could test ?

(note for myself:
*stopable 0/1)*

**Comment by empierre** [comment]
Hello,

  I've found back your backup from august 3, I have the stop button.

  can you update and retest? (please use update-mdah.sh script.

**Comment by justintime1976** [comment]
Hi,

 

Still no stopbutton for Zonnescherm!

 

Justin

 

Van: Emmanuel [mailto:notifications@github.com] 
Verzonden: dinsdag 8 september 2015 21:19
Aan: empierre/MyDomoAtHome <MyDomoAtHome@noreply.github.com>
CC: justintime1976 <jlcornelius76@gmail.com>
Onderwerp: Re: [MyDomoAtHome] Stop button Hasta blinds (#6)

 

Hello,

I've found back your backup from august 3, I have the stop button.

can you update and retest? (please use update-mdah.sh script.
