### ISSUE TITLE
error with dockerfile node.js

### ISSUE THREAD

**Issue by CondormanFr** [empierre/MyDomoAtHome#62]
Je viens de tester le dockerfile, mais il fait une erreur

```
Step 10 : RUN cd /src; npm install
 ---> Running in d1580cc1c0f4
[91mnpm[0m[91m [0m[91minfo it worked if it ends with ok
[0m[91mnpm info using npm@2.14.20
npm info using node@v4.4.0
[0m[91mnpm ERR! install Couldn't read dependencies
[0m[91mnpm ERR! Linux 3.13.0-40-generic
[0m[91mnpm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! path /src/package.json
npm ERR! code ENOPACKAGEJSON
[0m[91mnpm ERR! errno -2
npm ERR! syscall open

npm ERR! package.json ENOENT: no such file or directory, open '/src/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.
[0m[91m
npm ERR! Please include the following file with any support request:
npm ERR!     /src/npm-debug.log
[0mRemoving intermediate container d1580cc1c0f4
The command '/bin/sh -c cd /src; npm install' returned a non-zero code: 254
```

**Comment by empierre** [comment]
Bonjour Eric,

  Tu refais l'image ou tu utilises celle de Docker Hub ? 

  Je la fais tourner et n'ai pas de problème pour la faire, as-tu changé l'image de base ? 

  Normalement il récupère les données de github et installe les dépendances, ici on dirait qu'il ne trouve pas le clone de github

**Comment by CondormanFr** [comment]
Bonjour,
Je refais l'image (car je ne l'ai pas trouvé sur le hub de docker)
Donc j'ai juste fait un copié / collé du dockerfile et je laisse docker faire le reste.

**Comment by empierre** [comment]
il est ici: https://hub.docker.com/r/epierre/mdah/

**Comment by CondormanFr** [comment]
Merci. Ca fonctionne.
En revanche, je fais tourner docker sur mon synology et il y a une heure d'écart sur la machine virtuelle docker mdah comparé à l'heure du Synology...
21h40 en vrai et 20h40 dans le log de mdah. Du coup, les timestamp sont erronés.

**Comment by empierre** [comment]
Hello,

  ah une question amusante ;-) comment gérer l'heure... je me note le point. 

  quelle ligne de commande passes-tu dans synology ?  J'ai une personne qui essaye mais ne semble pas y arriver: http://www.domoticz.com/forum/viewtopic.php?p=79389#p79389

**Comment by CondormanFr** [comment]
Je n'ai pas utilisé la ligne de commande. Je passe par l'assistant. J'ai mis les captures d'écran si ça peut aider.

**Comment by empierre** [comment]
merci ! on va voir le retour

**Comment by empierre** [comment]
Bonsoir,

  regardes si ton problème de Timezone est réglé ainsi en passant TZ:

```
docker run --name=mdah --env DOMO="http://your_ip:8080" --env TZ=Europe/Paris -p 3002:3002 epierre/mdah
```

**Comment by CondormanFr** [comment]
Non, ce n’est pas mieux. J’ai toujours 1 H de décalage.

 J’ai essayé de builder le dernier fichier dockerfile mais j’ai toujours une erreur :

`Build failed: The command '/bin/sh -c cd /src; npm install' returned a non-zero code: 254`

Log complète ici : 
[](https://hub.docker.com/r/rgouyet/mydomoathome/builds/b7anb2sywqpdpbirom8dsa/)

**Comment by empierre** [comment]
et si tu mets ceci dans la ligne de commande:
-v /etc/localtime:/etc/localtime:ro

**Comment by empierre** [comment]
pour le problème de création d'image docker, je n'ai pas les moyens de tester là mais si tu changes dans le fichier:

RUN cd /src; npm install

en 

RUN cd /src/dist; npm install

est-ce que cela fonctionne ?

**Comment by CondormanFr** [comment]
Ce n’est pas possible car via l’assistant du synology, il n’est possible que de sélectionner des dossiers partagés du synology.

De : Emmanuel [mailto:notifications@github.com] 
Envoyé : mercredi 16 mars 2016 13:14
À : empierre/MyDomoAtHome MyDomoAtHome@noreply.github.com
Cc : CondormanFr github@gouyet.com
Objet : Re: [MyDomoAtHome] error with dockerfile node.js (#62)

et si tu mets ceci dans la ligne de commande:
-v /etc/localtime:/etc/localtime:ro

**Comment by empierre** [comment]
bon pas trop de solution, normalement j'ai mis dans le Dockerfile la timezone Europe/Paris

où vois-tu le décalage ?

**Comment by empierre** [comment]
sur mon syno dans /etc/localtime j'ai:
CET-1CEST,M3.5.0,M10.5.0/3

**Comment by empierre** [comment]
je viens de recréer une image, lors du build j'ai bien eu:

Current default time zone: 'Europe/Paris'
Local time is now:      Wed Mar 16 20:09:58 CET 2016.
Universal Time is now:  Wed Mar 16 19:09:58 UTC 2016.

**Comment by empierre** [comment]
normalement par l'environnement ça marche, essayes:

sudo docker run --rm -t -i ubuntu date
sudo docker run --rm -t -i -e "TZ=Europe/Paris" ubuntu date

**Comment by empierre** [comment]
there is a cli possibility to test this (here I can't mine is a DS215) : http://www.jinkit.com/docker-on-synology/

**Comment by empierre** [comment]
Bonjour Eric,

  J'ai totalement refait l'image docker pour qu'elle installe à partir du package et non du repository git, si tu as l'occasion de retester,

**Comment by CondormanFr** [comment]
Déjà ça compile bien sur le hub docker. 
A suivre ...

**Comment by CondormanFr** [comment]
[33mwarn[39m:    --minUptime not set. Defaulting to: 1000ms
stdout
11:59:40
[33mwarn[39m:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
stdout
11:59:40
[31merror[39m:   Cannot start forever
stdout
11:59:40
[31merror[39m:   script /src/mdah.js does not exist.
stdout
12:09:00
[33mwarn[39m:    --minUptime not set. Defaulting to: 1000ms
stdout
12:09:00
[33mwarn[39m:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
stdout
12:09:00
[31merror[39m:   Cannot start forever
stdout
12:09:00
[31merror[39m:   script /src/mdah.js does not exist.

**Comment by empierre** [comment]
oui le script plante donc forever arrête tout... argh une erreur en bas

**Comment by empierre** [comment]
je viens de faire la correction dans le Dockerfile

**Comment by CondormanFr** [comment]
Du coup, à présent, j'ai une erreur au niveau du build :   

`Build failed: The command '/bin/sh -c dpkg -i node-mydomoathome-latest.deb' returned a non-zero code: 1`

**Comment by empierre** [comment]
attention aux artéfacts, et au fait qu'il prenne un package en cache

je nettoye souvent ainsi:
sudo docker rmi $(sudo docker images -q)

**Comment by empierre** [comment]
no the issue is there, have to find how to circumvent this:

/var/lib/dpkg/info/mydomoathome.postinst: line 53: sudo: command not found

**Comment by empierre** [comment]
ok corrigé j'ai ajouté le package sudo ;-)

**Comment by CondormanFr** [comment]
Super. Build OK et fonctionnement OK.
Pour les heures, c'est OK aussi.
Bravo et merci.

Maintenant, il faudrait lier le dockerfile de ce projet github au build automatique du hub docker comme cela, les mises à jour seront automatiques quand il y a des évolutions.

**Comment by empierre** [comment]
en cours de build ici: https://hub.docker.com/r/epierre/iss-mdah

**Comment by CondormanFr** [comment]
Parfait. C'est plus simple. 
Merci

**Comment by empierre** [comment]
ayé, mis à jour dans la doc, merci de l'idée ! 

https://hub.docker.com/r/epierre/iss-mdah/

**Comment by CondormanFr** [comment]
Concernant le fichier config.json. 
J'ai essayé d'ajouter un lien de volume pour aller chercher /etc/mydomoathome/ sur un dossier de mon syno afin de conserver ou de pouvoir modifier le fichier config.json mais cela n'a pas marché. Peut-être faut il ajouter un `VOLUME /etc/mydomoathome` dans le dockerfile.

**Comment by CondormanFr** [comment]
Est-ce que le fichier config.json est crée lorsqu'il n'existe pas et que ça écrit "defaulting" ? (WARNING: /etc/mydomoathome/config.json not found, defaulting)

Sinon, existe-t-il un exemple de contenu ? Quelles sont les options de config paramétrable ?

**Comment by empierre** [comment]
ok pour rajouter VOLUME /etc/mydomoathome mais vers quelle destination ?

**Comment by empierre** [comment]
le contenu de config.json est normalement:
{
  "app_name": "MyDomoAtHome",
  "domo_path": "http://192.168.0.28:8080",
  "port": 3002
}

as-tu un moyen de voir s'il est bien crée? le mesage est quand domo_path n'est pas défini.

dans l'ordre:
environnement > valeur par défaut>fichier conf

**Comment by CondormanFr** [comment]
Je crois que l’instruction VOLUME est juste pour définir que ce répertoire peut être mappé ou non.

**Comment by CondormanFr** [comment]
A priori, même si actuellement, je défini un mapping avec le dossier /etc/mydomoathome, il n'en tient pas compte : 
Si je retire la variable d'environnement, il fait defaulting avec http://127.0.0.1:8080
Si je mets un fichier config.json dans le dossier mappé, cela ne change rien.

Il faudrait essayer de rajouter VOLUME /etc/mydomoathome à la fin du dockerfile et voir si du coup, il tient compte du répertoire mappé et de ce qu'il y a dedans.

**Comment by empierre** [comment]
ok rajouté pour voir.

normalement je peux demander à ce que la conf environnement soit enregistrée à partir de l'environnement. 

j'ai prévu aussi une IHM mais à venir encore

**Comment by CondormanFr** [comment]
Bon, ça n'a rien changé. il ne prend pas en compte mon fichier.

**Comment by empierre** [comment]
mais pour toi qu'est-ce qu'il faudrait faire ? l'environnement passé modifie le fichier de conf locale ?

**Comment by CondormanFr** [comment]
Proposition : 
Si pas d'environnement et pas de fichier de config => création d'un fichier de config avec les valeurs par défaut.
Si pas d'environnement et fichier de config présent => prise en compte du fichier de configuration

Après, s'il y a la variable d'environnement, je pense qu'elle doit prendre le dessus sur le fichier de config (pour l'adresse de domoticz, sinon, pour les autres paramètres, il faudrait prendre ce qu'il y a dans le fichier)

C'est mon avis mais je n'ai pas la prétention d'avoir raison.

**Comment by empierre** [comment]
on va tenter et voir, si tu as l'occasion de tester cela, je viens de modifier un peu l'ordre

**Comment by empierre** [comment]
Hello,

  J'ai renommé dans le Dockerfile le config.json car chez moi (en corrigeant la typo) il partait en erreur car il y avait le fichier sur le filesystem et dans le docker. Si tuas l'occasion de tester

**Comment by empierre** [comment]
Eris,

  as-tu pu retester ?

**Comment by CondormanFr** [comment]
Désolé, mon docker ne voulait plus télécharger l'image ...

Test de matin : 

si je ne mets pas d'information volume, j'ai cette erreur :  
`/usr/share/mydomoathome/app/node_modules/nconf/lib/nconf/stores/file.js:160
stdout
05:30:26
    throw new Error(&quot;Error parsing your configuration file: [&quot; + this.file + ']: ' + ex.message);
stdout
05:30:26
    ^
stdout
05:30:26
stdout
05:30:26
Error: Error parsing your configuration file: [/etc/mydomoathome/config.json]: EISDIR: illegal operation on a directory, read
stdout
05:30:26
`

si je mets une option volume pour mapper le **fichier** /etc/mydomoathome/config.json avec un fichier sur mon synology : 
`info: WARNING: /etc/mydomoathome/config.json not found, defaulting`

**Comment by empierre** [comment]
étrange comportement, je n'arrive pas à le reproduire... 

te dis-til quelle version il a pris ? 0.0.35 ?

**Comment by empierre** [comment]
Bonjour Eric,

  as-tu pu voir ? j'ai un autre utilisateur qui me demande de l'aide sur cela:

http://easydomoticz.com/forum/viewtopic.php?p=15786&sid=531a8cefca6e5cf00ea0e65d2f5bbf63#p15786

**Comment by empierre** [comment]
on dirait que le volume sur un fichier faisait tout planter, j'ai corrigé et la build a été relancée

**Comment by CondormanFr** [comment]
J'ai téléchargé la dernière image latest.
Avec cette ligne de commande, `docker run --name=mdah --env DOMO=http://192.168.1.xxx:xxxx --env TZ=Europe/Paris -p 3002:3002 epierre/mdah`

Ca plante dès le début 

```
[33mwarn[39m:    --minUptime not set. Defaulting to: 1000ms
stdout
20:34:47
[33mwarn[39m:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
stdout
20:34:48
[32minfo[39m:    Forever processing file: [90m/usr/share/mydomoathome/app/mdah.js[39m
stdout
20:35:02

```

Si j'essaie de mettre un volume, j'obtiens cette erreur de docker que je n'avais jamais eu:

`Start container mdah2 failed: Cannot start container bdec827567b88c52b709a17512d1bc89e4445ac55d47621bba337eb29347071a: [8] System error: not a directory`

Romain

**Comment by empierre** [comment]
étrange, sur le 1er on ne voit pas d'erreur. Ici j'ai ceci au démarrage:
WARNING: Error loading config file:stat /home/in/.docker/config.json: permission denied
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
warn: /etc/mydomoathome/config.json not found, defaulting
info: Domoticz server: http://192.168.0.28:8080
info: Node version: 4.4.0
info: MDAH version: MyDomoAtHome 0.0.48
info: OS version: Linux linux 4.2.0-34-lowlatency
info: Hostname: 958b3eb02b6f 172.17.0.6 in /root
info: MDAH port: 3002

**Comment by empierre** [comment]
https://github.com/docker/compose/issues/2268
ils recommendent un
docker inspect <container name>

**Comment by CondormanFr** [comment]
Je viens de tester la version v0.50
L'option volume fonctionne en pointant vers un dossier de mon syno où j'avais un fichier config.json
En revanche, les url "system" et "rooms" renvoient des données mais pas l'url "devices"

Même en supprimant le mapping vers le volume j'ai ce comportement.

Il y a cette erreur dans le log :  
`/usr/share/mydomoathome/app/mdah.js:163
stdout
11:48:10
    if (data.HaveDimmer==='true') {dimmable=1}else {dimmable=0};
stdout
11:48:10
        ^
stdout
11:48:10
stdout
11:48:10
ReferenceError: data is not defined
stdout
11:48:10
    at devSt (/usr/share/mydomoathome/app/mdah.js:163:6)
stdout
11:48:10
    at DevDoor (/usr/share/mydomoathome/app/mdah.js:430:25)
stdout
11:48:10
    at Request._callback (/usr/share/mydomoathome/app/mdah.js:1624:41)
stdout
11:48:10
    at Request.self.callback (/usr/share/mydomoathome/app/node_modules/request/request.js:199:22)
stdout
11:48:10
    at emitTwo (events.js:87:13)
stdout
11:48:10
    at Request.emit (events.js:172:7)
stdout
11:48:10
    at Request.&lt;anonymous&gt; (/usr/share/mydomoathome/app/node_modules/request/request.js:1036:10)
stdout
11:48:10
    at emitOne (events.js:82:20)
stdout
11:48:10
    at Request.emit (events.js:169:7)
stdout
11:48:10
    at IncomingMessage.&lt;anonymous&gt; (/usr/share/mydomoathome/app/node_modules/request/request.js:963:12)
stdout
11:48:10
error: Forever detected script exited with code: 1`

**Comment by empierre** [comment]
là c'est un bug chez moi, j'ai modifié du code à distance mais pas testé ;-( désolé... je corrige et relance une build

**Comment by CondormanFr** [comment]
J'ai une nouvelle erreur avec la nouvelle image : 

`/usr/share/mydomoathome/app/mdah.js:232
stdout
16:51:29
        default: rbl=Status;break;
stdout
16:51:29
                     ^
stdout
16:51:29
stdout
16:51:29
ReferenceError: Status is not defined
stdout
16:51:29
    at devSt (/usr/share/mydomoathome/app/mdah.js:232:16)
stdout
16:51:29
    at DevDimmer (/usr/share/mydomoathome/app/mdah.js:330:12)
stdout
16:51:29
    at Request._callback (/usr/share/mydomoathome/app/mdah.js:1612:41)
stdout
16:51:29
    at Request.self.callback (/usr/share/mydomoathome/app/node_modules/request/request.js:199:22)
stdout
16:51:29
    at emitTwo (events.js:87:13)
stdout
16:51:29
    at Request.emit (events.js:172:7)
stdout
16:51:29
    at Request.&lt;anonymous&gt; (/usr/share/mydomoathome/app/node_modules/request/request.js:1036:10)
stdout
16:51:29
    at emitOne (events.js:82:20)
stdout
16:51:29
    at Request.emit (events.js:169:7)
stdout
16:51:29
    at IncomingMessage.&lt;anonymous&gt; (/usr/share/mydomoathome/app/node_modules/request/request.js:963:12)
stdout
16:51:29
error: Forever detected script exited with code: 1`

**Comment by empierre** [comment]
attention maintenant je mais la version du package dans Dockerfile
le bug de ce jour est enfin corrigé, j'ai lancé les builds

**Comment by CondormanFr** [comment]
Le dernier build fait encore l'erreur à priori :  

`/usr/share/mydomoathome/app/mdah.js:232
stdout
18:13:10
        default: rbl=Status;break;
stdout
18:13:10
                     ^
stdout
18:13:10
stdout
18:13:10
ReferenceError: Status is not defined
stdout
18:13:10
    at devSt (/usr/share/mydomoathome/app/mdah.js:232:16)
stdout
18:13:10
    at DevDimmer (/usr/share/mydomoathome/app/mdah.js:330:12)
stdout
18:13:10
    at Request._callback (/usr/share/mydomoathome/app/mdah.js:1612:41)
stdout
18:13:10
    at Request.self.callback (/usr/share/mydomoathome/app/node_modules/request/request.js:199:22)
stdout
18:13:10
    at emitTwo (events.js:87:13)
stdout
18:13:10
    at Request.emit (events.js:172:7)
stdout
18:13:10
    at Request.&lt;anonymous&gt; (/usr/share/mydomoathome/app/node_modules/request/request.js:1036:10)
stdout
18:13:10
    at emitOne (events.js:82:20)
stdout
18:13:10
    at Request.emit (events.js:169:7)
stdout
18:13:10
    at IncomingMessage.&lt;anonymous&gt; (/usr/share/mydomoathome/app/node_modules/request/request.js:963:12)
stdout
18:13:10
error: Forever detected script exited with code: 1
stdout
18:13:10
error: Script restart attempt #3
stdout
18:13:12
warn: /etc/mydomoathome/config.json not found, defaulting
stdout
18:13:12
info: Domoticz server: http://192.168.1.110:8084
stdout
18:13:12
info: Node version: 4.4.0
stdout
18:13:12
info: MDAH version: MyDomoAtHome 0.0.50
stdout
18:13:12
info: OS version: Linux linux 3.10.35
stdout
18:13:12
info: Hostname: mdah 172.17.0.19 in /root
stdout
18:13:12
info: MDAH port: 3002
stdout
18:13:16
/usr/share/mydomoathome/app/mdah.js:232
stdout
18:13:16
        default: rbl=Status;break;
stdout
18:13:16
                     ^
stdout
18:13:16
stdout
18:13:16
ReferenceError: Status is not defined
stdout
18:13:16
    at devSt (/usr/share/mydomoathome/app/mdah.js:232:16)
stdout
18:13:16
    at DevDimmer (/usr/share/mydomoathome/app/mdah.js:330:12)
stdout
18:13:16
    at Request._callback (/usr/share/mydomoathome/app/mdah.js:1612:41)
stdout
18:13:16
    at Request.self.callback (/usr/share/mydomoathome/app/node_modules/request/request.js:199:22)
stdout
18:13:16
    at emitTwo (events.js:87:13)
stdout
18:13:16
    at Request.emit (events.js:172:7)
stdout
18:13:16
    at Request.&lt;anonymous&gt; (/usr/share/mydomoathome/app/node_modules/request/request.js:1036:10)
stdout
18:13:16
    at emitOne (events.js:82:20)
stdout
18:13:16
    at Request.emit (events.js:169:7)
stdout
18:13:16
    at IncomingMessage.&lt;anonymous&gt; (/usr/share/mydomoathome/app/node_modules/request/request.js:963:12)`

**Comment by empierre** [comment]
oui je viens de corriger, j'ai lancé une version 0.0.51

**Comment by CondormanFr** [comment]
Ok, avec le dernier build 0.0.52 tout est OK même avec le mapping vers le fichier config.json.
Bravo et merci.

**Comment by empierre** [comment]
ouf ;-) et merci aussi de ton aide
