### ISSUE TITLE
blind stoppable inverted

### ISSUE THREAD

**Issue by empierre** [empierre/MyDomoAtHome#74]

**Comment by empierre** [comment]
to check if this this issue:
https://www.domoticz.com/forum/viewtopic.php?f=21&t=6882&p=81488#p81488
"OpenZWave: Domoticz has send a Switch command!, Level: 255, NodeID: 20 (0x14)
That should be 0-100% I'd say..."

**Comment by jonferreira** [comment]
I have them as Blinds Percentage

`{
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Set Level: 97 %",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 13,
         "HardwareName" : "Aeotec Z-Stick Gen5",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00001401",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2016-03-31 18:04:05",
         "Level" : 97,
         "LevelInt" : 97,
         "MaxDimLevel" : 100,
         "Name" : "Guests Room Roller Shutter",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Set Level: 97 %",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Blinds Percentage",
         "SwitchTypeVal" : 13,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "blinds",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "180"
      }`

Not sure this is the JSON output you was looking for?

**Comment by jonferreira** [comment]
nvm, pretty sure you was looking for this:

`{"MaxDimLevel":100,"Action":6,"graph":null,"level":"info","message":"","timestamp":"2016-03-31T17:41:00.779Z"}
{"level":"info","message":"http://127.0.0.1:8080/json.htm?type=command&param=switchlight&idx=180&switchcmd=On&level=23&passcode=","timestamp":"2016-03-31T17:41:00.781Z"}
`

**Comment by jonferreira** [comment]
Problem is **switchcmd** is set to **On** when should be **Set Level**
:-)

**Comment by empierre** [comment]
version 0.0.52 going out to be tested

**Comment by jonferreira** [comment]
OK so I’ve updated MDAH to 0.0.53, restart service, restart Imperihome but so far haven’t noticed any difference. 

Actually I’ve noticed the Up/Down buttons seem to be swapped setting switch type to Blinds Percentage Inverted seems to fix it though.

**Down**
{"level":"info","message":"http://127.0.0.1:8080/json.htm?type=command&param=switchlight&idx=180&switchcmd=On&level=74&passcode=","timestamp":"2016-03-31T22:16:19.511Z"}
**Up**
{"level":"info","message":"http://127.0.0.1:8080/json.htm?type=command&param=switchlight&idx=180&switchcmd=Off&passcode=","timestamp":"2016-03-31T22:16:21.923Z"}
**10%**
{"level":"info","message":"http://127.0.0.1:8080/json.htm?type=command&param=switchlight&idx=180&switchcmd=On&level=10&passcode=","timestamp":"2016-03-31T22:17:04.431Z"}

**switchcmd** is still set to **On** - am I missing something?

**Comment by jonferreira** [comment]
looking at the last commit I've found this

```
case 6:
                     //Blinds -> On for Closed, Off for Open
                     if (actionParam == 100) {
-                        my_url = "/json.htm?type=command&param=switchlight&idx=" + deviceId + "&switchcmd=Off&level=" + actionParam + "&passcode=";
+                        my_url = "/json.htm?type=command&param=switchlight&idx=" + deviceId + "&switchcmd=Off&passcode=";
+                    } else if (actionParam == 0) {
+                        my_url = "/json.htm?type=command&param=switchlight&idx=" + deviceId + "&switchcmd=On&passcode=";
                     } else {
                         my_url = "/json.htm?type=command&param=switchlight&idx=" + deviceId + "&switchcmd=On&level=" + actionParam + "&passcode=";
                     }
```

I believe that

`my_url = "/json.htm?type=command&param=switchlight&idx=" + deviceId + "&switchcmd=On&level=" + actionParam + "&passcode=";`

should be changed to 

`my_url = "/json.htm?type=command&param=switchlight&idx=" + deviceId + "&switchcmd=Set Level&level=" + actionParam + "&passcode=";`

Edit:

I've tested this myself and seems to be working great

```
case 5:
                    //Blinds inverted
                    if (actionParam == 0) {
                        my_url = "/json.htm?type=command&param=switchlight&idx=" + deviceId + "&switchcmd=Off&passcode=";
                    } else if (actionParam == 100) {
                        my_url = "/json.htm?type=command&param=switchlight&idx=" + deviceId + "&switchcmd=On&passcode=";
                    } else {
                        lsetLevel = Math.ceil(actionParam * (device_tab[deviceId].MaxDimLevel) / 100);
                        logger.info(actionParam+" "+lsetLevel);
                        my_url = "/json.htm?type=command&param=switchlight&idx=" + deviceId + "&switchcmd=Set%20Level&level=" + lsetLevel + "&passcode=";
                    }
                    break;
                case 6:
                    //Blinds -> On for Closed, Off for Open
                    if (actionParam == 100) {
                        my_url = "/json.htm?type=command&param=switchlight&idx=" + deviceId + "&switchcmd=Off&passcode=";
                    } else if (actionParam == 0) {
                        my_url = "/json.htm?type=command&param=switchlight&idx=" + deviceId + "&switchcmd=On&passcode=";
                    } else {
                        my_url = "/json.htm?type=command&param=switchlight&idx=" + deviceId + "&switchcmd=Set%20Level&level=" + actionParam + "&passcode=";
                    }
                    break;
                default:
                    lsetLevel = Math.ceil(actionParam * (device_tab[deviceId].MaxDimLevel) / 100);
                    my_url = "/json.htm?type=command&param=switchlight&idx=" + deviceId + "&switchcmd=Set%20Level&level=" + lsetLevel + "&passcode=";
                    break;
```
