### ISSUE TITLE
RGB lamps

### ISSUE THREAD

**Issue by matthijsberk** [empierre/MyDomoAtHome#8]
I would like to control my rgblights (milight) with imperihome from domoticz controller. *offtopic great work, Imperihome is exactly what I was looking for. *

**Comment by empierre** [comment]
@matthijsberk can you send me your domoticz database to domoticz@e-nef.com so I can test the configuration ?

**Comment by empierre** [comment]
Question 559 to Domoticz Team
https://www.domoticz.com/forum/tracker.php?p=1&t=599

**Comment by matthijsberk** [comment]
Thank you, I did some research, because I try to find out how to make it easier for you. What I found out is that milight doesn't need saturation, because it doesn't have support for it so I think it's always 100% saturation (I tested it with a conversion calculator from hsl to rgb) (fixed value for saturation and onlythe brightness and hue are editable). What's strange is that domoticz supports philips hue lights, which has saturation control. So your question remains and I'm very curious what the answer will be. Thank you for the great support.

**Comment by empierre** [comment]
I've upped the subject on the forum since the ticket has been closed for it
is a forum discussion.

**Comment by Damien630** [comment]
Thank you for that wonderful work. I am also very interested about controlling my rgb lights (milight) with imperihome from domoticz. Any news about a next release including that feature ? thanks

**Comment by empierre** [comment]
no,  some values are still missing in domoticz,  a ticket is still open

**Comment by empierre** [comment]
some news here, will start testing soon
https://github.com/domoticz/domoticz/issues/292#issuecomment-170317081

**Comment by matthijsberk** [comment]
Well that's some positive news. I'm curious what the outcome is and if it's enough for imperihome.

**Comment by empierre** [comment]
ok being added to the new version, to test follow the instrictions here:
https://github.com/empierre/MyDomoAtHome/tree/nodejs

**Comment by empierre** [comment]
https://github.com/domoticz/domoticz/issues/292
