### ISSUE TITLE
set dimmer slider to 0% when dimmer is turned off

### ISSUE THREAD

**Issue by jonferreira** [empierre/MyDomoAtHome#81]
as discussed in https://www.domoticz.com/forum/viewtopic.php?f=21&t=6882&start=520#p80890

both Fibaro and Qubino can "save" last dimming value - it's based on a parameter.

with Vera when you turn off a dimmer it will show 0% dimming and if you turn on (turn On command, not set value) the dimmer itself with go back to the last dimming position (assuming you have enabled this functionality)

I always have this enabled so what was happening with Vera + Imperihome was if I turn off a dimmer IH would report 0% level, turn on would send a "On" command which would dim to the last known level (all handled by the dimmer itself, i.e. dimmer would turn on and immediately report dimming value)

**Comment by MarcusKlerks** [comment]
Same is valid for (my) Popp dimmers (default) so count my vote in if latency is not getting too great.

**Comment by empierre** [comment]
ok what happens is that Imperihome always send a value for on or off, so I cannot guess if the user saif "Off" or slided to 0, same for On or slided to 100%
GET /devices/464/action/setLevel/100
GET /devices/464/action/setLevel/0

**Comment by empierre** [comment]
the command has set in DZ to 0 the dimming value
/json.htm?type=command&param=switchlight&idx=455&switchcmd=On&passcode=

can you test on 0.0.53 antd tell me ?

**Comment by jonferreira** [comment]
not sure I understood what you want me to test I'm afraid :-(

**Comment by MarcusKlerks** [comment]
On 0.0.53 my (Popp) dimmer is off and the slider is on 45% (latest dim value). Hope this is what you wanted to know?

**Comment by jonferreira** [comment]
same with my dimmers, no visible difference from latest version

**Comment by jonferreira** [comment]
So I took a while to read through your - beautiful - mdah.js code and did the following change in DevDimmer(data)

```
params=[];
    params.push({"key": "Status", "value": status.toString()});
    if (data.Status.match(/Off/)) {
        params.push({"key": "Level", "value":0});
    } else {
        params.push({"key": "Level", "value": data.Level.toString()});
    }
```

this does exactly what I was saying: if a dimmer is Off then report Level as 0

*_However *_ it seems to be working only when I reload Imperihome and I have no idea why, when I turn off a dimmer I can see DevDimmer getting called and replying correctly 

```
{"AddjMulti":1,"AddjMulti2":1,"AddjValue":0,"AddjValue2":0,"BatteryLevel":255,"CustomImage":0,"Data":"Off","Description":"","Favorite":0,"HardwareID":13,"HardwareName":"Aeotec Z-Stick Gen5","HardwareType":"OpenZWave USB","HardwareTypeVal":21,"HaveDimmer":true,"HaveGroupCmd":true,"HaveTimeout":false,"ID":"00000701","Image":"Light","IsSubDevice":false,"LastUpdate":"2016-04-01 10:33:38","Level":54,"LevelInt":54,"MaxDimLevel":100,"Name":"Master Bedroom Light","Notifications":"false","PlanID":"8","PlanIDs":[8],"Protected":false,"ShowNotifications":true,"SignalLevel":"-","Status":"Off","StrParam1":"","StrParam2":"","SubType":"Switch","SwitchType":"Dimmer","SwitchTypeVal":7,"Timers":"false","Type":"Light/Switch","TypeImg":"dimmer","Unit":1,"Used":1,"UsedByCamera":false,"XOffset":"0","YOffset":"0","idx":"120","level":"info","message":"","timestamp":"2016-04-01T09:33:40.969Z"}
{"id":"120","name":"Master Bedroom Light","type":"DevDimmer","room":"Switches","params":[{"key":"Status","value":"0"},{"key":"Level","value":0}],"level":"info","message":"","timestamp":"2016-04-01T09:33:40.972Z"}

```

**Comment by empierre** [comment]
beware of the working stuff behind (cascading):
- when you action something, IH changes locally (aka visually) the status while sending the order to MDAH
- MDAH receives the ordre, translates it to DZ
- DZ sends the order to hardware, and updates its JSON status
- on next IH refresh(normal or forced), it polls MDAH that polls DZ, and returns a status.

So what you immediatly see may not be the target state, but a transient one.

I've not understood your last point, what do you see ? or when ?

**Comment by jonferreira** [comment]
Yeah I'm sure you are right on this one @empierre :-)

> I've not understood your last point, what do you see ? or when ?

I've added a debug output to the end of DevDimmer funtion

```
logger.info(data);
logger.info(myfeed);
```

This outputs the above JSON when I click OFF which seems to indicate IH is querying the device state and MDAH is replying with **Level = 0** (after the change I've made) but the slider isn't updated accordingly so i'm clearly missing the point here.

If I force a IH refresh then all OFF dimmers report a 0% Level as intended

**Comment by empierre** [comment]
@jonferreira I try to stitch to https://github.com/airbnb/javascript for the code, I hope this is good, sometimes there is too much hack hidden between some switches I should document more...

so are you ok with your code above ? can you propose a pull request ?

**Comment by jonferreira** [comment]
It's still not perfect so i'll need a bit more time to figure out why this is *_only *_working for manual IH refreshes
Will update here when I figure it out :-)

**Comment by empierre** [comment]
corrected a bug, DZ is ternary for dimmers, maybe that will help

**Comment by jonferreira** [comment]
hmm apt-cache policy mydomoathome shows that last available version is still 0.0.53...maybe I'm missing something?

**Comment by empierre** [comment]
something went strange...

try:
apt-get remove mydomoathome
apt-get install MyDomoAtHome

**Comment by jonferreira** [comment]
done although it installed 0.053 again...
looking at http://www.e-nef.com/domoticz/mdah/ sounds like the latest version is 0.1.7?

**Comment by jonferreira** [comment]
OK so since I couldn't install it with apt-get I worked my way around it

wget http://www.e-nef.com/domoticz/mdah/node-mydomoathome-latest.deb
sudo dpkg -i node-mydomoathome-latest.deb

**Comment by MarcusKlerks** [comment]
Testing  with a virtual device: system is less responsive and I'm looking now at a situation where the dimmer in DZ is On and it is showing Off in IH. The slider is NOT at zero in IH but reflects the situation of DZ. So my conclusion at this moment is that it is not working for a virtual device. Will test with  'real' device later.

**Comment by empierre** [comment]
well tell me what you see, and be sure to indicatye if this is a normal or inverted. Some reported it fine (mostly RGB testers) so I thought this owuld be good now

**Comment by MarcusKlerks** [comment]
DZ: v3.5065; MDAH: 0.1.17
**Testing dimmer (Virtual, Lighting2)**
Start situation:        DZ: dimmer Off, slider at 60%; IH: dimmer Off, slider at 60%
DZ turn dimmer On:  DZ: dimmer On, slider at 60%; IH: dimmer On, slider at 60%
DZ turn dimmer Off: DZ: dimmer Off, slider at 60%; IH: dimmer Off, slider at 60%
IH turn dimmer On:  DZ: dimmer On, slider at 60%; IH: dimmer On, slider at 60%
IH turn dimmer Off: DZ: dimmer Off, slider at 60%; IH: dimmer Off, slider at 60%
DZ move slider 46%: DZ: dimmer On, slider at 46%; IH: dimmer On, slider at 46%
DZ turn dimmer Off: DZ: dimmer Off, slider at 50%; IH: dimmer Off, slider at 46%

Tested about (slightly different slider values) the same with a 'real' (Popp) dimmer with the same results. For me this is okay though, I'm used to the DZ behaviour

**Comment by empierre** [comment]
great ! thanks for all those tests !
