### ISSUE TITLE
Selector Switch

### ISSUE THREAD

**Issue by houk001** [empierre/MyDomoAtHome#95]
Hello 
When using selector switch from domoticz its working ok, but when i change it from ImperiHome the switch set for good value and 1-2 seconds later switch to off. 

version 0.1.16
and version 0.1.17

**Comment by jonferreira** [comment]
it appears to be working fine on my end, can you please try again with the latest v0.1.19?

**Comment by houk001** [comment]
Tested on 0.1.19 Still the same 
I even delete from names in this switch any character that is specified to my language limiting it to standard us and still setting any option switch to off from imperihome 
This selector switch goes to off also in domoticz

Also in 0.1.19 all devices is in rooms, not like earlier in switches, temps, utility etc. Thanks for that
EDIT: Also Temp Graph is working again

**Comment by empierre** [comment]
@houk001 can you send me the /json.htm?type=devices&filter=all&used=true&order=Name for your selector switch device so I try to see if there is something special around ?

there used to have issue if you use space in the list items, but this is in imperihome

**Comment by houk001** [comment]
of course :D 
{
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Set Level: 20 %",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 6,
         "HardwareName" : "dummy",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00014055",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2016-04-18 09:31:40",
         "Level" : 20,
         "LevelActions" : "|||",
         "LevelInt" : 20,
         "LevelNames" : "Off|Alarm Noc|Alarm Góra|Alarm All",
         "LevelOffHidden" : false,
         "MaxDimLevel" : 100,
         "Name" : "Alarm Switch",
         "Notifications" : "false",
         "PlanID" : "13",
         "PlanIDs" : [ 13 ],
         "Protected" : false,
         "SelectorStyle" : 0,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Set Level: 20 %",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Selector Switch",
         "SwitchType" : "Selector",
         "SwitchTypeVal" : 18,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "Light",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "6"
      },

**Comment by empierre** [comment]
@houk001 try to remove the white space (or add an underscore) and tell me. 

If this is confirmed, I'll push back to Imperihome team the subject

**Comment by houk001** [comment]
Confirmed. After remove white spaces from level names its working.

**Comment by empierre** [comment]
ok I'll push that back to Imperihome team(again)

**Comment by empierre** [comment]
zendesk imperihome #4760

**Comment by sorampage** [comment]
Hi,
i have a similar problem .. I use a selector with http request for IR climatisation controler.
When i use the selector from domoticz, all is ok. But when i use the same selector from ImperiHome, the same request is sent ... OFF ... always, for any level selector.

**Comment by empierre** [comment]
cannot reproduce 0.2.29
